// Guide data for the Dawnwalker tracker. Tips and gamerscore come from the IGN wiki
// (https://www.ign.com/wikis/the-blood-of-dawnwalker/Achievements_and_Trophies).
// Keys are lower-case Steam API names, so Steam unlocks match exactly.
// `steps` become a per-achievement checklist saved in the browser.
// `flag` marks achievements that need planning: "ending" (one per playthrough,
// keep a save before the finale) or "run" (a whole-run condition).
window.GUIDE = {
  appid: "3751260",
  title: "The Blood of Dawnwalker",
  titleAccent: "Dawnwalker",
  subtitle: "Achievement tracker, synced from Steam",
  credit: "Guide tips from the IGN wiki.",
  storageKey: "dawnwalker-tracker-v1",
  pointsLabel: "Gamerscore (Xbox values)",
  pointsNote: "Steam has no points. These are the Xbox values IGN lists.",
  pointsSuffix: "G",
  flags: {
    ending: { label: "Ending: one per playthrough", tone: "accent" },
    run: { label: "Whole-run condition", tone: "accent2" },
  },
  highlight: { flag: "ending", label: "Remaining endings", note: "Keep a save before the finale" },
  categories: [
    ["story", "Story"],
    ["endings", "Endings"],
    ["quests", "Questlines"],
    ["bosses", "Bosses"],
    ["combat", "Combat & Skills"],
    ["explore", "Exploration"],
    ["gear", "Gear & Economy"],
  ],
  achievements: {
    ach_a_dawnwalker_is_born: { cat: "story", g: 10,
      tip: "Complete the prologue by finishing the Bad Blood quest." },
    ach_the_blood_of_dawnwalker: { cat: "story", g: 10,
      tip: "Finish the game with any ending." },
    ach_in_the_nick_of_time: { cat: "story", g: 10, flag: "run",
      tip: "Finish the game within 30 in-game days to rescue Coen's family." },
    ach_easier_than_ever: { cat: "story", g: 100, flag: "run",
      tip: "Beat the whole game on the Duelist difficulty preset." },

    ach_the_turncoat: { cat: "endings", g: 50, flag: "ending",
      tip: "Make a deal with Brencis during A Deal With the Devil, Midnight Reckoning, or A Lone Wolf's Hunt." },
    ach_the_omen_bringer: { cat: "endings", g: 50, flag: "ending",
      tip: "Finish Lacra's questline, then finish the game with the Midnight Reckoning quest." },
    ach_the_knyazmaker: { cat: "endings", g: 50, flag: "ending",
      tip: "Finish Crake's questline, then finish the game with the Rise at Dawn quest." },
    ach_the_folk_hero: { cat: "endings", g: 50, flag: "ending",
      tip: "Defeat Brencis on your own and finish the game by completing A Deal With the Devil." },
    ach_the_coward: { cat: "endings", g: 10, flag: "ending",
      tip: "Secret ending: leave Vale Sangora through an exit at the southeastern edge of the map." },
    ach_eternal_bliss: { cat: "endings", g: 10, flag: "ending",
      tip: "Secret ending: repeat the loop four times in the dream sequence during the Home Sweet Home quest." },

    ach_sins_of_the_past: { cat: "quests", g: 10,
      tip: "Complete Anca's entire questline.",
      steps: ["Echoes of Silenced Bells", "Between the Words", "Where Old Devils Lie", "Stronger Than Achilles"] },
    ach_nightbloom: { cat: "quests", g: 10,
      tip: "Complete Lacra's entire questline.",
      steps: ["A Friend Like This", "Song of the Mountain", "Hive and Seek", "Our Rotten Roots", "The Night of Horrors"] },
    ach_always_hiding: { cat: "quests", g: 10,
      tip: "Complete Crake's entire questline.",
      steps: ["The Firebrand", "Shadow in the Woods", "Where Loyalty Lies", "What Hunts the Night", "What Moves the Dead", "Distant Shadows", "A Closer Look"] },
    ach_the_unquenchable_thirst: { cat: "quests", g: 10,
      tip: "Complete Vicho's questline, starting with A Study in Crimson in Svartrau.",
      steps: ["A Study in Crimson", "The Good Samaritan"] },
    ach_the_outcast: { cat: "quests", g: 10,
      tip: "Complete Ocha's questline, starting with The Heart Wants What It Wants in Svartrau." ,
      steps: ["The Heart Wants What It Wants"] },
    ach_tsarinas_pet: { cat: "quests", g: 10,
      tip: "Complete every sanzhani quest in Vale Sangora, starting with Good Home outside Svartrau.",
      steps: ["Good Home", "Come Hither", "Burrow Sorrows", "Pearly and Precious", "Tiny Dancer"] },
    ach_arbiters_blade: { cat: "quests", g: 20,
      tip: "Complete Forge It Anew and restore the Sword of St Mihai." },
    ach_arbiters_regalia: { cat: "quests", g: 20,
      tip: "Complete A Bulwark Against Darkness and unlock the Arbiter armour set." },

    ach_the_right_fist_of_the_knyaz: { cat: "bosses", g: 10,
      tip: "Defeat Ambrus in The Gilded Gauntlet quest." },
    ach_the_mad_khan: { cat: "bosses", g: 10,
      tip: "Defeat Bakir in The Lunar Game quest." },
    ach_the_dark_mistress: { cat: "bosses", g: 10,
      tip: "Defeat Xanthe in The Cycle of Love quest. She can also be found inside the Svartrau cathedral at night." },

    ach_master_of_defence: { cat: "combat", g: 10,
      tip: "Block in the direction of an enemy's attack at the last second for a Perfect Block. Do it five times in a row without taking damage." },
    ach_overkill: { cat: "combat", g: 10,
      tip: "Hex an enemy with Burning Blood (Witchcraft), then kill them with Artery Strike (Swordmastery). The strike must decapitate, which only happens by chance." },
    ach_burst_like_a_bubble: { cat: "combat", g: 10,
      tip: "Kill an enemy with the Blood Surge Vampiric ability." },
    ach_all_for_me: { cat: "combat", g: 10,
      tip: "Unlock extra ability slots in any skill tree, then equip three Passive Abilities at once." },
    ach_primal_instinct: { cat: "combat", g: 10,
      tip: "Enter a conversation while your Vampiric health is low. Coen drains the person automatically." },
    ach_like_shadow: { cat: "combat", g: 10,
      tip: "Travel 1000 metres as a wolf using the Shapeshift ability." },
    ach_dead_echoes: { cat: "combat", g: 10,
      tip: "Use the Compel Soul Witchcraft ability. IGN notes you can do it during the tutorial with Anca." },
    ach_master_of_arms: { cat: "combat", g: 20,
      tip: "Spend 35 skill points in Swordmastery to unlock the ultimates, then pick one of the three." },
    ach_arch_warlock: { cat: "combat", g: 20,
      tip: "Spend 35 skill points in Witchcraft to unlock the ultimates, then pick one of the three." },
    ach_creature_of_the_night: { cat: "combat", g: 20,
      tip: "Spend 35 skill points in Vampirism to unlock the ultimates, then pick one of the three." },
    ach_practice_makes_perfect: { cat: "combat", g: 10,
      tip: "Fully level up any one skill in the three skill trees." },
    ach_a_quick_learner: { cat: "combat", g: 20,
      tip: "Reach the level cap of 50." },
    ach_balanced_diet: { cat: "combat", g: 10,
      tip: "Drink blood with Voracious Bite on any target 10 times." },

    ach_where_am_i: { cat: "explore", g: 10,
      tip: "Progress Lacra's questline, or drink the blood of Ambrus, Xanthe, or Bakir after defeating them." },
    ach_antiquarian: { cat: "explore", g: 10,
      tip: "Enter any ancient ruin. Quests like Deep Down or Xanthe's Excavations: Unsealed Secrets lead to them." },
    ach_metropolitan: { cat: "explore", g: 10,
      tip: "Visit Svartrau for the first time." },
    ach_valley_trotter: { cat: "explore", g: 10,
      tip: "Visit all eight settlements. Uriashi Village opens only after A Friend Like This and Song of the Mountain.",
      steps: ["Laslea", "Military Camp", "Maragir", "Parlita", "Svartrau", "Tantari", "Oghasti", "Uriashi Village"] },
    ach_stunning_views: { cat: "explore", g: 10,
      tip: "Climb every tower in Vale Sangora and fully scout each point of interest." },
    ach_capture_the_flag: { cat: "explore", g: 10,
      tip: "Destroy every flag in Svartrau. They hang above the major gates and have their own map icon." },
    ach_delivery_delay: { cat: "explore", g: 10,
      tip: "Take out roaming vrakhiri transport squads. The Court menu offers quests such as Ambrus's Transports: Roadside Surprise and Bloody Business." },
    ach_infamous: { cat: "explore", g: 10,
      tip: "Reach the maximum Infamy level." },

    ach_golden: { cat: "gear", g: 20,
      tip: "Put a Legendary item in every equipment slot. Forge It Anew and A Bulwark Against Darkness give legendary gear." },
    ach_selfish: { cat: "gear", g: 10,
      tip: "Sell a fish to any fishmonger." },
    ach_miser: { cat: "gear", g: 10,
      tip: "Hold 5000 denarii at once." },
    ach_smuggler: { cat: "gear", g: 10,
      tip: "Sell 1000 denarii worth of valuables to the Silver Trader in Svartrau." },
  },
};
