// Guide data for the Valheim tracker (achievements added in the 1.0 release, September 2026).
// Sources:
// - Steam guide "Valheim: 100% Achievement Guide" by Tudzer, and its comment thread
//   (https://steamcommunity.com/sharedfiles/filedetails/?id=3799211007). Its author read the
//   requirements from the game files. The creature, trophy, fish, dish and food checklists below
//   come from the guide's tracker spreadsheet
//   (https://docs.google.com/spreadsheets/d/1Hc167FeYYJlXQUui1SCOazS0LH-6N3wpdy4UAz7-wZw).
// - VGTimes "Valheim Achievement Guide: How to Unlock All 53 Achievements"
//   (https://vgtimes.com/guides/168632-valheim-achievement-guide-how-to-unlock-all-53-achievements.html).
// - Steam discussions on seasonal pieces and the Pathfinder
//   (https://steamcommunity.com/app/892970/discussions/0/3826415117586337647/,
//   https://steamcommunity.com/app/892970/discussions/0/525387040750089473/).
// - Obliterator recipe: GamesRadar (https://www.gamesradar.com/valheim-thunder-stone-obliterator/).
// General rules, per the Steam guide:
// - Mods disable achievements. Some console commands flag the character as a cheater. To clear
//   the flag, enable the console in Gameplay settings, press F5 and enter
//   yesiuseddevcommandsbutiwantmyachievementsanyway
// - Progress is per character, not per world.
// - The game has its own progress lists: press Tab, open Trophies, click the achievement icon.
//   Entries you still miss show as ???.
// Keys are lower-case Steam API names, so Steam unlocks match exactly.
// `steps` become a per-achievement checklist saved in the browser.
window.GUIDE = {
  appid: "892970",
  title: "Valheim",
  titleAccent: "heim",
  subtitle: "Achievement tracker, synced from Steam",
  credit: "Tips from Tudzer's Steam guide \"Valheim: 100% Achievement Guide\" and its tracker spreadsheet, cross-checked with VGTimes and Steam discussions.",
  defaultStatus: "todo",
  colors: {
    light: { accent: "#2c6a7c", accent2: "#b4531a" },
    dark: { accent: "#7ec8dc", accent2: "#f29a5c" },
  },
  flags: {
    hard: { label: "Hard combat difficulty", tone: "accent" },
    streak: { label: "No-death streak", tone: "accent" },
    setting: { label: "Needs a world modifier", tone: "accent" },
    death: { label: "Deliberate death", tone: "accent2" },
    season: { label: "Real-world calendar", tone: "accent2" },
    coop: { label: "Needs a second player", tone: "accent2" },
  },
  highlight: { flag: "hard", label: "Hard difficulty left", note: "Set the Combat modifier to Hard" },
  categories: [
    ["hard", "Hard difficulty"],
    ["bosses", "Bosses"],
    ["deaths", "Deaths"],
    ["explore", "Exploration & sailing"],
    ["building", "Building"],
    ["collect", "Collections"],
    ["counters", "Counters"],
    ["meta", "Meta achievements"],
  ],
  achievements: {
    // Hard difficulty. Plan a separate Hard world or switch the Combat modifier for these.
    allbosseshard: { cat: "hard", flag: "hard", wide: true,
      tip: ["Kill all 8 bosses with the Combat modifier on Hard. Edit the world's modifiers from the world list; you can switch to Hard just for the boss fights and back afterwards.",
            "You may change other modifiers too: Death Penalty, Resource Rate, Portals, No Build Cost and Passive Enemies. Two players in the guide's comments report that a world labelled Custom still counts as long as Combat is Hard. The guide author first said a Custom world would not count, then withdrew that.",
            "Cheese: weaken a boss on an easier setting, leave, switch to Hard, then land the kill.",
            "The Tough Viking unlocks along the way."],
      steps: ["Eikthyr", "The Elder", "Bonemass", "Moder", "Yagluth", "The Seeker Queen", "Fader", "Kall Fimbulbringer"] },
    killallcreatureshard: { cat: "hard", flag: "hard", wide: true,
      tip: ["Kill every creature on this list with the Combat modifier on Hard. It covers the same 108 entries as The Hunter, so do both at once.",
            "Tame and friendly creatures count: hens, piggies, calves, cubs, hatchlings, captives in the Deep North, and your own summons. Enable friendly fire (the PvP toggle) to hit your own summons: Staff of the Wild roots, Trollstav trolls, Dead Raiser skeletons, Spirit Caller spirits.",
            "Kall Fimbulbringer counts twice (phase 1 and phase 3). Each boss Aspect in the Deep North counts separately.",
            "The guide author says the required list changed after a patch; this list is his updated one. Check the in-game list (Tab, Trophies, achievement icon) for ??? entries if it does not pop."],
      steps: [
        "Meadows: Boar",
        "Meadows: Piggy",
        "Meadows: Deer",
        "Meadows: Eikthyr",
        "Meadows: Greyling",
        "Meadows: Neck",
        "Black Forest: Root",
        "Black Forest: Bear",
        "Black Forest: Chicken",
        "Black Forest: The Elder",
        "Black Forest: Ghost",
        "Black Forest: Greydwarf",
        "Black Forest: Greydwarf Brute",
        "Black Forest: Greydwarf Shaman",
        "Black Forest: Hen",
        "Black Forest: T.W.I.G.",
        "Black Forest: Skeleton",
        "Black Forest: Brenna",
        "Black Forest: Rancid Remains",
        "Black Forest: Troll",
        "Swamp: Abomination",
        "Swamp: Blob",
        "Swamp: Oozer",
        "Swamp: Kvastur",
        "Swamp: Bonemass",
        "Swamp: Draugr",
        "Swamp: Draugr Elite",
        "Swamp: Leech",
        "Swamp: Surtling",
        "Swamp: Wraith",
        "Swamp: Writhan",
        "Mountain: Bat",
        "Mountain: Frost Blob",
        "Mountain: Moder",
        "Mountain: Fenring",
        "Mountain: Cultist",
        "Mountain: Geirrhafa",
        "Mountain: Drake",
        "Mountain: Stone Golem",
        "Mountain: Ulv",
        "Mountain: Wolf",
        "Mountain: Wolf Cub",
        "Plains: Growth",
        "Plains: Deathsquito",
        "Plains: Fuling",
        "Plains: Fuling Berserker",
        "Plains: Zil & Thungr",
        "Plains: Yagluth",
        "Plains: Fuling Shaman",
        "Plains: Zil",
        "Plains: Lox",
        "Plains: Lox Calf",
        "Plains: Vile",
        "Ocean: Serpent",
        "Mistlands: Dvergr Rogue",
        "Mistlands: Dvergr Mage",
        "Mistlands: Gjall",
        "Mistlands: Hare",
        "Mistlands: Seeker",
        "Mistlands: Seeker Brood",
        "Mistlands: Seeker Soldier",
        "Mistlands: The Queen",
        "Mistlands: Skelett",
        "Mistlands: Tick",
        "Ashlands: Asksvin",
        "Ashlands: Asksvin Hatchling",
        "Ashlands: Lava Blob",
        "Ashlands: Bonemaw",
        "Ashlands: Charred Marksman",
        "Ashlands: Summoned Charred Warrior",
        "Ashlands: Charred Warlock",
        "Ashlands: Charred Warrior",
        "Ashlands: Lord Reto",
        "Ashlands: Charred Twitcher",
        "Ashlands: Summoned Twitcher",
        "Ashlands: Fader",
        "Ashlands: Fallen Valkyrie",
        "Ashlands: Morgen",
        "Ashlands: Summoned Troll",
        "Ashlands: Volture",
        "Deep North: Aspect of the Writhing Dead",
        "Deep North: Aspect of the Lightning Stag",
        "Deep North: Aspect of the Living Forest",
        "Deep North: Aspect of the Emerald Flame",
        "Deep North: Aspect of the Dragon Mother",
        "Deep North: Aspect of the Crawling Matriarch",
        "Deep North: Aspect of the Twisted Soul",
        "Deep North: Barka",
        "Deep North: Spiritcaller Bjorn",
        "Deep North: Shapeless Pulp",
        "Deep North: Tiny Pulp",
        "Deep North: Spiritcaller Boar",
        "Deep North: Imprisoned Dvergr",
        "Deep North: Elaking",
        "Deep North: Eyeless One",
        "Deep North: Fallen Warrior",
        "Deep North: Kall Fimbulbringer (Phase 1)",
        "Deep North: Kall Fimbulbringer (Phase 3)",
        "Deep North: Captive Fuling",
        "Deep North: Krigen",
        "Deep North: Hexen",
        "Deep North: Moose",
        "Deep North: Moose Calf",
        "Deep North: Spiritcaller Moose",
        "Deep North: Seal",
        "Deep North: Baby Seal",
        "Deep North: Gammeltroll",
        "Deep North: Spiritcaller Wolf",
      ] },

    // Bosses
    boss1eikthyr: { cat: "bosses",
      tip: "Place 2 Deer Trophies on the altar in the Meadows to summon Eikthyr." },
    boss2elder: { cat: "bosses",
      tip: "Burn 3 Ancient Seeds (dropped by Greydwarf nests in the Black Forest) at The Elder's altar." },
    boss3bonemass: { cat: "bosses",
      tip: "Offer 10 Withered Bones at Bonemass's altar in the Swamp. Bring poison resistance mead and blunt weapons." },
    boss4moder: { cat: "bosses",
      tip: "Place 3 Dragon Eggs from the Mountains on Moder's altar. Bring frost resistance and a bow." },
    boss5yagluth: { cat: "bosses",
      tip: "Place 5 Fuling Totems on Yagluth's altar in the Plains." },
    boss6queen: { cat: "bosses",
      tip: "Enter the Infested Citadel in the Mistlands with a Sealbreaker. The first fight needs no sacrifice." },
    boss7fader: { cat: "bosses",
      tip: "Find 9 Bell Fragments in Charred Fortresses in the Ashlands, craft 3 Bells, and ring them at Fader's altar." },
    boss8frozenking: { cat: "bosses",
      tip: "Bring 3 Malicious Blood to Kall Fimbulbringer's altar in the Deep North." },
    allbosses: { cat: "bosses", wide: true,
      tip: ["Defeat all 8 bosses on the same character, on any difficulty. Kills from before the 1.0 release do not count.",
            "The Tough Viking (Normal or higher) and The Toughest Viking (Hard) track separately. If you play on Hard from the start, all three unlock together."],
      steps: ["Eikthyr", "The Elder", "Bonemass", "Moder", "Yagluth", "The Seeker Queen", "Fader", "Kall Fimbulbringer"] },
    allbossesnormal: { cat: "bosses", wide: true,
      tip: "Defeat all 8 bosses with the Combat modifier on Normal or higher. Casual or Easy kills do not count. It completes alongside The Toughest Viking.",
      steps: ["Eikthyr", "The Elder", "Bonemass", "Moder", "Yagluth", "The Seeker Queen", "Fader", "Kall Fimbulbringer"] },
    allminibosses: { cat: "bosses",
      tip: ["Kill all five minibosses. Zil and Thungr count as two.",
            "Hildir's quests reveal the first three dungeons. Lord Reto guards his tomb in the Ashlands and drops the Dyrnwyn hilt fragment, which The Chosen One needs."],
      steps: ["Brenna (Smouldering Tomb, Black Forest)", "Geirrhafa (Howling Cavern, Mountains)", "Zil (Sealed Tower, Plains)", "Thungr (Sealed Tower, Plains)", "Lord Reto (his tomb, Ashlands)"] },
    soloboss: { cat: "bosses",
      tip: "Kill any boss with no other player in the fight. Eikthyr is the easiest." },
    multiplayerboss: { cat: "bosses", flag: "coop",
      tip: "Kill any boss while another player takes part in the fight. Boss achievements count for every participant, so a friend can carry you through Eikthyr." },

    // Deaths. Do these before The Survivor streak or after it pops.
    firstdeath: { cat: "deaths", flag: "death",
      tip: "Die once, from anything. It unlocks with your first death in any of the other death achievements." },
    deathbytree: { cat: "deaths", flag: "death",
      tip: "Eat no food so you sit at base health, chop a tall tree, and stand where the trunk falls. It unlocks with your first death in the every-tree achievement below." },
    deathbytreeall: { cat: "deaths", flag: "death", wide: true,
      tip: ["Die to a falling tree of each of the 10 kinds. Arrive with no food eaten so one hit kills you.",
            "Swamp trees, Yggdrasil Shoots, Ashlands trees and Deep North trees need higher-tier axes.",
            "The two Deep North trees both show as Timber Tree in-game. They look different: die to each look once."],
      steps: ["Beech (Meadows)", "Birch (Meadows, Plains)", "Oak (Meadows)", "Fir (Meadows, Black Forest)", "Pine (Black Forest)",
              "Swamp Tree (Swamp)", "Yggdrasil Shoot (Mistlands)", "Ashlands Tree (Ashlands)", "Snow Fir (Deep North)", "Snow Pine (Deep North)"] },
    deathbyobliterator: { cat: "deaths", flag: "death",
      tip: "Build an Obliterator (8 Iron, 4 Copper, 1 Thunder Stone, near a Forge; Haldor sells the Thunder Stone for 50 coins after you kill The Elder). Empty your inventory, pull the lever and stay close when the lightning strikes. This also covers the Obliterator death in Are You Alright?" },
    deathbyalltypes: { cat: "deaths", flag: "death", wide: true,
      tip: ["Die once to each of the 16 causes the game tracks, per the Steam guide's reading of the game files. Pick a safe spot for your tombstone and carry nothing you need.",
            "Stalactite: stand under a falling ice stalactite in a Mountain Frost Cave. Catapult: VGTimes says the catapult itself must kill you, for example its support landing on you while you place it; its projectiles do not count. Ballista: stand in front of one and let it fire (Charred Fortresses in the Ashlands have them). These three are the least documented."],
      steps: ["Creature hit", "Fall damage", "Drowning", "Burning (stand in a campfire)", "Freezing (Mountains at night, no frost resistance)",
              "Poison (Leeches or Blobs)", "Smoke (enclosed room with a fire)", "Falling off the edge of the world (see The Legends Are True)",
              "Falling tree", "Ballista", "Stalactite", "Catapult", "Ashlands ocean (boiling water)", "Obliterator", "Drawbridge (close one on yourself)", "Ashlands lava"] },

    // Exploration & sailing
    arrived: { cat: "explore",
      tip: "Enter a game world. Valheim is the tenth world of the Norse cosmos, so this pops the first time you spawn in after the 1.0 release." },
    explorensew: { cat: "explore", wide: true,
      tip: ["Reach about 10,350 m from the world center toward the north, south, east and west. The directions track separately.",
            "Do it together with The Pathfinder. The world edge sits at about 10,500 m: slow down so you do not fall off. A Longship is the fastest boat. The trips also feed The Sailor and The Captain."],
      steps: ["North (Deep North)", "South (Ashlands)", "East", "West"] },
    explorensewnomap: { cat: "explore", flag: "setting", wide: true,
      tip: ["Same as The Explorer, with the No Map world modifier on.",
            "Cheese, confirmed by the guide author: reach each edge with the map on, log out, switch No Map on in the world's modifiers, log back in, and move a little so the game registers the stat. Switch it off again afterwards."],
      steps: ["North", "South", "East", "West"] },
    sailedge: { cat: "explore", flag: "death",
      tip: ["Sail to the world edge (about 10,500 m from the center) and over it. You fall, die and lose the boat and everything you carry, so bring only the boat and nothing you need.",
            "This also covers the edge-of-the-world death in Are You Alright?"] },
    grindsail: { cat: "explore",
      tip: "Sail 131,946 m in total, twice the world's circumference. Riding as a passenger counts. Leave it for last and let the Explorer trips and The Captain feed it." },
    grindsailhelm: { cat: "explore",
      tip: "Sail 65,973 m (one circumference) while you steer. The four Explorer trips out and back cover about 84 km of steering, so combine them." },
    grindleviathan: { cat: "explore",
      tip: ["Find a Leviathan (a huge shell-backed creature) in the Ocean. Save and relog first; several players report it helps.",
            "Mine its Abyssal Barnacles with a pickaxe until it wakes and dives. Stay near the center of its back until it is fully underwater: the game checks your distance when it leaves."] },
    grindtreasure: { cat: "explore",
      tip: ["Dig up and open 10 buried treasure chests. The Wishbone (dropped by Bonemass) pings when you are near one.",
            "Reported cheese: opening the same chest ten times counted, in multiplayer and in single player."] },

    // Building
    buildhouse: { cat: "building",
      tip: "Build an enclosed house with at least 6 floor pieces, 8 walls, 4 roof pieces, 1 piece of furniture (a bed) and 1 chest. VGTimes also lists 1 light source; add a torch to be safe." },
    buildvillage: { cat: "building", wide: true,
      tip: ["Place at least this many pieces from each build category. The Steam guide lists them as build-menu categories. VGTimes reads the first line as 10 separate houses; if the count stalls, build extra small houses.",
            "Check which tab of the Hammer menu each piece sits in."],
      steps: ["10 Building", "40 Flooring", "40 Walls", "20 Roofing", "10 Architecture", "10 Furniture", "5 Lighting", "5 Decor"] },
    grindbuild: { cat: "building",
      tip: "Have 500 building pieces standing. One tester found that placing and removing the same piece did not count, while a base built with No Build Cost did, as long as all 500 stayed standing." },
    grindcomfort: { cat: "building", wide: true,
      tip: ["Reach comfort 20 where you rest. Only the best item of each comfort group counts, so stack different groups. This setup gives 22 per the Steam guide and needs Ashlands materials.",
            "The seasonal Maypole and Yule Tree add comfort too, but you can only build them in season."],
      steps: ["Hearth", "Dragon Bed", "Bear, Wolf or Lox Rug", "Jute Banner", "Fairy Lights or Flower Garland", "Any Throne", "Round Table or Long Heavy Table",
              "Item Stand or Armor Stand", "Lit Hot Tub", "Lava Lantern", "Asksvin Skeleton or Pots"] },
    buildhigh: { cat: "building",
      tip: ["Build a structure at least 49 m tall, per the game files. Type /pos in chat at the base, build up, and check again.",
            "Wood Iron Poles and Beams, stone or Black Marble keep structural support far enough up. Build on flat, low ground."] },
    buildhighworld: { cat: "building",
      tip: ["Place a building piece at least 492 m above level zero (the Y value that /pos shows), per the Steam guide's reading of the game files.",
            "Sources disagree: VGTimes says 432 m, and one player's in-game tracker showed a target of 432. Aim for 492 to be safe.",
            "Find a Mountain peak with a Y of about 440 to 450 (the guide author used valheim-map.world with Y coordinates enabled) and build a tower on it."] },
    allbuildpieces: { cat: "building", flag: "season", wide: true,
      tip: ["Build every piece in the Hammer menu once, about 400 pieces per the guide's spreadsheet. No Build Cost works for this one, and you can dismantle pieces afterwards. Use the in-game list to find what remains.",
            "The Steam guide also says to repair any item once.",
            "Seasonal pieces count. You can only build them during their real-world event; one Steam thread reports that changing the PC clock unlocks them. Built pieces stay after the season ends."],
      steps: ["Every crafting station and upgrade", "Every boat (Raft, Karve, Longship, Drakkar) and the Cart", "Siege pieces: Ballista, Battering Ram, Catapult",
              "Midsummer: Maypole", "Halloween: Jack-o-turnip", "Yule: Yule Tree, Yule Wreath, Yule Garland, Mistletoe, 3 Yuleklapp presents",
              "Mysterious Rock: pick up the rare StoneRock item (one spawn per biome; find it with valheim.gaming.tools/resource-nodes/stonerock), then build it",
              "Repair any item once"] },

    // Collections
    killallcreatures: { cat: "collect", wide: true,
      tip: ["Kill one of each creature on any difficulty. Do it on Hard to get The Master Hunter at the same time.",
            "Tame animals, captives and your own summons count. Enable friendly fire (the PvP toggle) to hit your own summons."],
      steps: [
        "Meadows: Boar",
        "Meadows: Piggy",
        "Meadows: Deer",
        "Meadows: Eikthyr",
        "Meadows: Greyling",
        "Meadows: Neck",
        "Black Forest: Root",
        "Black Forest: Bear",
        "Black Forest: Chicken",
        "Black Forest: The Elder",
        "Black Forest: Ghost",
        "Black Forest: Greydwarf",
        "Black Forest: Greydwarf Brute",
        "Black Forest: Greydwarf Shaman",
        "Black Forest: Hen",
        "Black Forest: T.W.I.G.",
        "Black Forest: Skeleton",
        "Black Forest: Brenna",
        "Black Forest: Rancid Remains",
        "Black Forest: Troll",
        "Swamp: Abomination",
        "Swamp: Blob",
        "Swamp: Oozer",
        "Swamp: Kvastur",
        "Swamp: Bonemass",
        "Swamp: Draugr",
        "Swamp: Draugr Elite",
        "Swamp: Leech",
        "Swamp: Surtling",
        "Swamp: Wraith",
        "Swamp: Writhan",
        "Mountain: Bat",
        "Mountain: Frost Blob",
        "Mountain: Moder",
        "Mountain: Fenring",
        "Mountain: Cultist",
        "Mountain: Geirrhafa",
        "Mountain: Drake",
        "Mountain: Stone Golem",
        "Mountain: Ulv",
        "Mountain: Wolf",
        "Mountain: Wolf Cub",
        "Plains: Growth",
        "Plains: Deathsquito",
        "Plains: Fuling",
        "Plains: Fuling Berserker",
        "Plains: Zil & Thungr",
        "Plains: Yagluth",
        "Plains: Fuling Shaman",
        "Plains: Zil",
        "Plains: Lox",
        "Plains: Lox Calf",
        "Plains: Vile",
        "Ocean: Serpent",
        "Mistlands: Dvergr Rogue",
        "Mistlands: Dvergr Mage",
        "Mistlands: Gjall",
        "Mistlands: Hare",
        "Mistlands: Seeker",
        "Mistlands: Seeker Brood",
        "Mistlands: Seeker Soldier",
        "Mistlands: The Queen",
        "Mistlands: Skelett",
        "Mistlands: Tick",
        "Ashlands: Asksvin",
        "Ashlands: Asksvin Hatchling",
        "Ashlands: Lava Blob",
        "Ashlands: Bonemaw",
        "Ashlands: Charred Marksman",
        "Ashlands: Summoned Charred Warrior",
        "Ashlands: Charred Warlock",
        "Ashlands: Charred Warrior",
        "Ashlands: Lord Reto",
        "Ashlands: Charred Twitcher",
        "Ashlands: Summoned Twitcher",
        "Ashlands: Fader",
        "Ashlands: Fallen Valkyrie",
        "Ashlands: Morgen",
        "Ashlands: Summoned Troll",
        "Ashlands: Volture",
        "Deep North: Aspect of the Writhing Dead",
        "Deep North: Aspect of the Lightning Stag",
        "Deep North: Aspect of the Living Forest",
        "Deep North: Aspect of the Emerald Flame",
        "Deep North: Aspect of the Dragon Mother",
        "Deep North: Aspect of the Crawling Matriarch",
        "Deep North: Aspect of the Twisted Soul",
        "Deep North: Barka",
        "Deep North: Spiritcaller Bjorn",
        "Deep North: Shapeless Pulp",
        "Deep North: Tiny Pulp",
        "Deep North: Spiritcaller Boar",
        "Deep North: Imprisoned Dvergr",
        "Deep North: Elaking",
        "Deep North: Eyeless One",
        "Deep North: Fallen Warrior",
        "Deep North: Kall Fimbulbringer (Phase 1)",
        "Deep North: Kall Fimbulbringer (Phase 3)",
        "Deep North: Captive Fuling",
        "Deep North: Krigen",
        "Deep North: Hexen",
        "Deep North: Moose",
        "Deep North: Moose Calf",
        "Deep North: Spiritcaller Moose",
        "Deep North: Seal",
        "Deep North: Baby Seal",
        "Deep North: Gammeltroll",
        "Deep North: Spiritcaller Wolf",
      ] },
    findalltrophies: { cat: "collect", wide: true,
      tip: ["Pick up one of each of the 68 trophies. The guide author says the list leaves out the Troll Trophy.",
            "Boss trophies drop on the boss kill. Hunt the rest while working on The Hunter."],
      steps: [
        "Meadows: Boar Trophy",
        "Meadows: Deer Trophy",
        "Meadows: Eikthyr Trophy",
        "Meadows: Neck Trophy",
        "Black Forest: Bear Trophy",
        "Black Forest: Ghost Trophy",
        "Black Forest: Greydwarf Trophy",
        "Black Forest: Greydwarf Brute Trophy",
        "Black Forest: Greydwarf Shaman Trophy",
        "Black Forest: Skeleton Trophy",
        "Black Forest: Brenna Trophy",
        "Black Forest: Rancid Remains Trophy",
        "Black Forest: The Elder Trophy",
        "Swamp: Abomination Trophy",
        "Swamp: Blob Trophy",
        "Swamp: Bonemass Trophy",
        "Swamp: Draugr Trophy",
        "Swamp: Draugr Elite Trophy",
        "Swamp: Kvastur Trophy",
        "Swamp: Leech Trophy",
        "Swamp: Surtling Trophy",
        "Swamp: Wraith Trophy",
        "Swamp: Writhan Trophy",
        "Mountain: Frost Blob Trophy",
        "Mountain: Cultist Trophy",
        "Mountain: Geirrhafa Trophy",
        "Mountain: Moder Trophy",
        "Mountain: Fenring Trophy",
        "Mountain: Drake Trophy",
        "Mountain: Stone Golem Trophy",
        "Mountain: Ulv Trophy",
        "Mountain: Wolf Trophy",
        "Plains: Vile Trophy",
        "Plains: Deathsquito Trophy",
        "Plains: Fuling Trophy",
        "Plains: Fuling Berserker Trophy",
        "Plains: Thungr Trophy",
        "Plains: Zil Trophy",
        "Plains: Yagluth Trophy",
        "Plains: Fuling Shaman Trophy",
        "Plains: Growth Trophy",
        "Plains: Lox Trophy",
        "Ocean: Serpent Trophy",
        "Mistlands: Dvergr Trophy",
        "Mistlands: Gjall Trophy",
        "Mistlands: Hare Trophy",
        "Mistlands: Seeker Trophy",
        "Mistlands: Seeker Soldier Trophy",
        "Mistlands: The Queen Trophy",
        "Mistlands: Tick Trophy",
        "Ashlands: Asksvin Trophy",
        "Ashlands: Lava Blob Trophy",
        "Ashlands: Bonemaw Trophy",
        "Ashlands: Marksman Trophy",
        "Ashlands: Warlock Trophy",
        "Ashlands: Warrior Trophy",
        "Ashlands: Fader Trophy",
        "Ashlands: Fallen Valkyrie Trophy",
        "Ashlands: Morgen Trophy",
        "Ashlands: Volture Trophy",
        "Deep North: Barka Trophy",
        "Deep North: Pulp Trophy",
        "Deep North: Elaking Trophy",
        "Deep North: Krigen Trophy",
        "Deep North: Hexen Trophy",
        "Deep North: Eyeless One Trophy",
        "Deep North: Moose Trophy",
        "Deep North: Seal Trophy",
      ] },
    grindfish: { cat: "collect", wide: true,
      tip: "Catch one of each of the 12 fish with a Fishing Rod and reel it all the way in. Grabbing a fish off the line or by hand does not count. Each entry shows the biome and bait.",
      steps: [
        "Perch (Meadows, Black Forest; Fishing Bait)",
        "Pike (Meadows, Black Forest; Fishing Bait)",
        "Trollfish (Black Forest; Mossy Fishing Bait)",
        "Giant Herring (Swamp; Sticky Fishing Bait)",
        "Tetra (Mountain (Frost Caves); Cold Fishing Bait)",
        "Grouper (Plains; Stingy Fishing Bait)",
        "Tuna (Ocean; Heavy Fishing Bait)",
        "Coral Cod (Ocean; Heavy Fishing Bait)",
        "Pufferfish (Ocean, Mistlands; Misty Fishing Bait)",
        "Anglerfish (Mistlands; Misty Fishing Bait)",
        "Northern Salmon (Deep North; Cold Fishing Bait)",
        "Magmafish (Ashlands; Hot Fishing Bait)",
      ] },
    bigfish: { cat: "collect",
      tip: ["Catch any 4-star fish with the rod and reel it all the way in. It looks much bigger than normal fish.",
            "Wear the Fishing Hat, raise Fishing skill and bring stamina food. Players report you can catch one by hand, drop it into a small pond, and recatch it with the rod."] },
    builddyrnwyn: { cat: "collect",
      tip: ["Collect the Hilt fragment from Lord Reto, then the Blade and Tip fragments at the locations that runestones in Putrid Holes (Ashlands) reveal.",
            "Craft Dyrnwyn at a level 4 Black Forge with the three fragments, 20 Flametal and a Bloodstone. One player had to craft it again after 1.0 for it to count."] },
    allweaponcraft: { cat: "collect",
      tip: "Craft every weapon, including every elemental variant of the Ashlands and Deep North weapons and the Grappling Hook. The Artisan list covers every weapon except the Torch, so work from that list and craft one Torch." },
    allitemcraft: { cat: "collect", wide: true,
      tip: ["Craft every item, about 415 entries in the guide's spreadsheet: armor, every weapon variant, arrows and bolts, mead bases, bombs, capes, trinkets, Cast items, feasts, bait and uncooked dishes. Save it for the late game.",
            "Work from the in-game list; the spreadsheet is too long for a checklist here.",
            "Unclear: whether Hildir's dresses and hats count. Buying them did not tick them off for one player."] },
    allfoodcooked: { cat: "collect", wide: true,
      tip: "Cook each of these 82 dishes: cooking-station meats, cauldron dishes, oven dishes, and the uncooked and unbaked prep items.",
      steps: [
        "Meadows: Cooked Boar Meat",
        "Meadows: Grilled Neck Tail",
        "Meadows: Cooked Deer Meat",
        "Black Forest: Boar Jerky",
        "Black Forest: Carrot Soup",
        "Black Forest: Cooked Egg",
        "Black Forest: Deer Stew",
        "Black Forest: Raw Fish",
        "Black Forest: Minced Meat Sauce",
        "Black Forest: Pulled Bear",
        "Black Forest: Queen's Jam",
        "Black Forest: Cooked Fish",
        "Black Forest: Cooked Chicken Meat",
        "Black Forest: Cooked Bear Meat",
        "Swamp: Black Soup",
        "Swamp: Sausages",
        "Swamp: Muckshake",
        "Swamp: Turnip Stew",
        "Mountain: Eyescream",
        "Mountain: Onion Soup",
        "Mountain: Wolf Jerky",
        "Mountain: Wolf Skewer",
        "Mountain: Cooked Wolf Meat",
        "Plains: Blood Pudding",
        "Plains: Bread Dough",
        "Plains: Fish Wraps",
        "Plains: Unbaked Lox Pie",
        "Plains: Unbaked Sweetbread",
        "Plains: Cooked Lox Meat",
        "Plains: Lox Meat Pie",
        "Plains: Bread",
        "Plains: Frosted Sweetbread",
        "Ocean: Serpent Stew",
        "Ocean: Cooked Serpent Meat",
        "Mistlands: Uncooked Fish 'n' Bread",
        "Mistlands: Uncooked Honey Glazed Chicken",
        "Mistlands: Uncooked Stuffed Mushroom",
        "Mistlands: Uncooked Meat Platter",
        "Mistlands: Uncooked Misthare Supreme",
        "Mistlands: Mushroom Omelette",
        "Mistlands: Salad",
        "Mistlands: Seeker Aspic",
        "Mistlands: Yggdrasil Porridge",
        "Mistlands: Cooked Hare Meat",
        "Mistlands: Cooked Seeker Meat",
        "Mistlands: Fish 'n' Bread",
        "Mistlands: Meat Platter",
        "Mistlands: Honey Glazed Chicken",
        "Mistlands: Misthare Supreme",
        "Ashlands: Fiery Svinstew",
        "Ashlands: Marinated Greens",
        "Ashlands: Mashed Meat",
        "Ashlands: Uncooked Piquant Pie",
        "Ashlands: Uncooked Roasted Crust Pie",
        "Ashlands: Scorching Medley",
        "Ashlands: Sizzling Berry Broth",
        "Ashlands: Sparkling Shroomshake",
        "Ashlands: Spicy Marmalade",
        "Ashlands: Cooked Volture Meat",
        "Ashlands: Cooked Asksvin Tail",
        "Ashlands: Cooked Bonemaw Meat",
        "Ashlands: Stuffed Mushroom",
        "Ashlands: Roasted Crust Pie",
        "Ashlands: Piquant Pie",
        "Deep North: Unbaked Poteitr",
        "Deep North: Fish Soup",
        "Deep North: Raw Kale Chips",
        "Deep North: Lingonberry Juice",
        "Deep North: Meatballs and Poteitr",
        "Deep North: Meat In Bread",
        "Deep North: Oatmeal",
        "Deep North: Oat Milk",
        "Deep North: Oven Pancake Batter",
        "Deep North: Pancakes",
        "Deep North: Seal Meat Soup",
        "Deep North: Smoked Fish",
        "Deep North: Smoked Moose Meat",
        "Deep North: Cooked Moose Meat",
        "Deep North: Cooked Seal Blubber",
        "Deep North: Oven Pancake",
        "Deep North: Kale Chips",
        "Deep North: Baked Poteitr",
      ] },
    allfoodeaten: { cat: "collect", wide: true,
      tip: ["Eat each of these 96 items. Cooking is not enough. The feasts count.",
            "The September 25, 2026 patch removed the unobtainable Blue Mushroom from the requirement."],
      steps: [
        "Meadows: Cooked Deer Meat",
        "Meadows: Cooked Boar Meat",
        "Meadows: Deer Stew",
        "Meadows: Whole Roasted Meadow Boar",
        "Meadows: Honey",
        "Meadows: Mushroom",
        "Meadows: Grilled Neck Tail",
        "Meadows: Raspberries",
        "Black Forest: Blueberries",
        "Black Forest: Boar Jerky",
        "Black Forest: Carrot",
        "Black Forest: Carrot Soup",
        "Black Forest: Cooked Bear Meat",
        "Black Forest: Cooked Chicken Meat",
        "Black Forest: Cooked Egg",
        "Black Forest: Black Forest Buffet Platter",
        "Black Forest: Cooked Fish",
        "Black Forest: Honey Glazed Chicken",
        "Black Forest: Minced Meat Sauce",
        "Black Forest: Pulled Bear",
        "Black Forest: Queen's Jam",
        "Swamp: Black Soup",
        "Swamp: Swamp Dweller's Delight",
        "Swamp: Yellow Mushroom",
        "Swamp: Sausages",
        "Swamp: Muckshake",
        "Swamp: Turnip Stew",
        "Mountain: Cooked Wolf Meat",
        "Mountain: Eyescream",
        "Mountain: Hearty Mountain Logger's Stew",
        "Mountain: Onion",
        "Mountain: Onion Soup",
        "Mountain: Wolf Jerky",
        "Mountain: Wolf Skewer",
        "Plains: Blood Pudding",
        "Plains: Bread",
        "Plains: Cloudberries",
        "Plains: Cooked Lox Meat",
        "Plains: Plains Pie Picnic",
        "Plains: Fish Wraps",
        "Plains: Lox Meat Pie",
        "Plains: Frosted Sweetbread",
        "Ocean: Sailor's Bounty",
        "Ocean: Cooked Serpent Meat",
        "Ocean: Serpent Stew",
        "Mistlands: Cooked Seeker Meat",
        "Mistlands: Cooked Hare Meat",
        "Mistlands: Mushrooms Galore a la Mistlands",
        "Mistlands: Fish 'n' Bread",
        "Mistlands: Stuffed Mushroom",
        "Mistlands: Meat Platter",
        "Mistlands: Misthare Supreme",
        "Mistlands: Jotun Puffs",
        "Mistlands: Magecap",
        "Mistlands: Mushroom Omelette",
        "Mistlands: Royal Jelly",
        "Mistlands: Salad",
        "Mistlands: Seeker Aspic",
        "Mistlands: Yggdrasil Porridge",
        "Ashlands: Cooked Asksvin Tail",
        "Ashlands: Cooked Bonemaw Meat",
        "Ashlands: Cooked Volture Meat",
        "Ashlands: Ashlands Gourmet Bowl",
        "Ashlands: Fiddlehead",
        "Ashlands: Fiery Svinstew",
        "Ashlands: Marinated Greens",
        "Ashlands: Mashed Meat",
        "Ashlands: Smoke Puff",
        "Ashlands: Piquant Pie",
        "Ashlands: Roasted Crust Pie",
        "Ashlands: Scorching Medley",
        "Ashlands: Sizzling Berry Broth",
        "Ashlands: Sparkling Shroomshake",
        "Ashlands: Spicy Marmalade",
        "Ashlands: Vineberry Cluster",
        "Deep North: Baked Poteitr",
        "Deep North: Cooked Moose Meat",
        "Deep North: Cooked Seal Blubber",
        "Deep North: Northern Morning Fare",
        "Deep North: Fish Soup",
        "Deep North: Luminous Larva",
        "Deep North: Kale",
        "Deep North: Kale Chips",
        "Deep North: Lingonberries",
        "Deep North: Lingonberry Juice",
        "Deep North: Meatballs and Poteitr",
        "Deep North: Meat In Bread",
        "Deep North: Oats",
        "Deep North: Oatmeal",
        "Deep North: Oat Milk",
        "Deep North: Oven Pancake",
        "Deep North: Pancakes",
        "Deep North: Poteitr",
        "Deep North: Seal Meat Soup",
        "Deep North: Smoked Fish",
        "Deep North: Smoked Moose Meat",
      ] },

    // Counters
    grindtrees: { cat: "counters",
      tip: "Fell 500 trees. Use your best axe. Meadows beech and birch fall fastest." },
    grindcook: { cat: "counters",
      tip: "Cook 100 dishes. Place several Cooking Stations over one fire to cook many pieces of meat at once." },
    grindharvest: { cat: "counters",
      tip: "Harvest 500 crops. Replant as you harvest; regrown crops count." },
    grindforager: { cat: "counters",
      tip: ["Pick 250 times from berry bushes and 250 times from mushrooms. The count is picks, not items: a Magecap pick that drops 3 counts once.",
            "Cloudberry patches in the Plains are the fastest berries. Plant Jotun Puffs or Magecaps from the Mistlands and harvest them for mushrooms."] },
    grindhoney: { cat: "counters",
      tip: "Harvest 500 Honey. Each Beehive makes about 1 Honey every 20 minutes and holds 4. Build a dozen hives early and empty them whenever you pass." },
    grindeat: { cat: "counters",
      tip: "Eat 500 food items. Keep your three food slots full during normal play." },
    grinddays: { cat: "counters", flag: "streak",
      tip: ["Survive 30 in-game days in a row without dying. A full day lasts 30 real minutes, so plan for up to 15 hours of play.",
            "Finish the death achievements before you start or after it pops. Stay near a safe base and skip risky trips. Sleeping skips most of the night, which should shorten the wait; no source confirms it."] },

    // Meta achievements
    kingsqueens: { cat: "meta", wide: true,
      tip: "Unlocks when you hold all six component achievements.",
      steps: ["The Viking", "The Hunter", "The Artisan", "The Master Chef", "The Carpenter", "The Explorer"] },
    childofodin: { cat: "meta", flag: "hard", wide: true,
      tip: ["Unlocks when you hold all four component achievements.",
            "Before the September 25, 2026 patch it failed to unlock on Steam for some players even when the game showed it done. The patch fixed it; the guide author knows no way to retrigger it for players hit by the bug."],
      steps: ["The Toughest Viking", "The Master Hunter", "The Survivor", "The Pathfinder"] },
  },
};
