// Guide data for the RuneScape: Dragonwilds tracker.
// Tips come mainly from the official RuneScape: Dragonwilds Wiki
// (https://dragonwilds.runescape.wiki/w/Steam_Achievements), its per-achievement pages,
// spell pages, quest list (https://dragonwilds.runescape.wiki/w/Quests), Agility course list
// (https://dragonwilds.runescape.wiki/w/Agility_Course), boss strategy pages, skill training
// guides (for example https://dragonwilds.runescape.wiki/w/Agility_training) and the XP table
// (https://dragonwilds.runescape.wiki/w/Experience).
// XP-per-kill and Construction XP-per-build figures come from Dragonwilds Codex
// (https://dragonwildscodex.com/guides/leveling/construction/), a fan site that states its
// data is verified for patch 0.12.1, so treat those numbers as approximate after 1.0.
// The game left Early Access with 1.0 on 15 September 2026. 1.0 changed some unlock levels
// (Magical Mending 27 -> 56 Artisan, Runes to Rune Essence 27 -> 61 Runecrafting), and later
// patches can change them again.
// Keys are lower-case Steam API names, so Steam unlocks match exactly.
// `steps` become a per-achievement checklist saved in the browser.
// `flag` marks planning concerns: "spell" (needs a skill spell or perk at a set level)
// and "grind" (a level 99 grind).
window.GUIDE = {
  appid: "1374490",
  title: "RuneScape: Dragonwilds",
  titleAccent: "Dragonwilds",
  subtitle: "Achievement tracker, synced from Steam",
  credit: "Tips from the official RuneScape: Dragonwilds Wiki, with XP rates from Dragonwilds Codex. Checked against the 1.0 release.",
  defaultStatus: "todo",
  colors: {
    light: { accent: "#b0401a", accent2: "#1c7a6c" },
    dark: { accent: "#ff8a5c", accent2: "#5fd3c0" },
  },
  flags: {
    spell: { label: "Needs a skill spell or perk", tone: "accent" },
    grind: { label: "Level 99 grind", tone: "accent2" },
  },
  highlight: { flag: "grind", label: "Level 99s left", note: "Each 99 needs 1,000,000 XP" },
  categories: [
    ["story", "Story bosses"],
    ["quests", "Regional quests"],
    ["novice", "Skill basics"],
    ["veteran", "Skill challenges"],
    ["hidden", "Hidden extras"],
    ["agility", "Agility courses"],
    ["mastery", "Level 99 mastery"],
  ],
  achievements: {
    // Story bosses. Each boss ends one primary quest, and the quests run in a fixed order:
    // Dragon Slayer, Withering Heights, Black Knight's Fortress, Icthlarin's Little Helper, Regicide.
    defeatvelgar: { cat: "story",
      tip: ["Defeat Velgar at the end of the Dragon Slayer quest. Start it with the Wise Old Man in Bramblemead Village.",
            "Carry the horn to the top of Velgar's Rise in the Fractured Plains (Ghornfell) and place it on the dragonkin altar. Wear power level 4 gear.",
            "Velgar is immune to poison and burning, so skip weapon poison and fire. Bring antipoison and healing food. He flies off at each quarter of his health, bombs the arena with poison, then lands on the next corner clockwise.",
            "A character that beat Velgar before achievements existed can climb Velgar's Rise and fight him again."] },
    defeatimaru: { cat: "story",
      tip: ["Defeat Imaru at the end of Withering Heights. It needs Dragon Slayer. Start it with the Wise Old Man near Ashien's Watch.",
            "Collect the three curse fragments first: grief (the shrines in Emberwood), rage (Lake of Lost Souls) and despair (Silverthorn Keep). Then open the seal in the tower in Hope's Fall.",
            "Wear power level 5 gear. Imaru is immune to poison, burning and bleed, so use water or air damage. She heals by devouring souls in her rift phase."] },
    defeatblackknighttitan: { cat: "story",
      tip: ["Defeat the Black Knight Titan in Part IV of Black Knight's Fortress (Dowdun Reach). It needs Withering Heights. Start it with Death in the Forgotten Temple.",
            "The quest needs Cooking 41 to cook maple sap into maple syrup. It also needs a steel spade, a steel or mithril pickaxe, a mithril logging axe and a fishing rod.",
            "Restore the Dreaming Stone, pass its barrier and climb The Bastion. Unlock all the nodestones first, or the barrier may not let you through.",
            "Wear power level 6 gear. The Titan is weak to crush and water, resists fire and slash, and is immune to burning, bleed and poison. Bring antifire potions.",
            "Old characters can re-fight him in his arena in The Bastion or in the Nightmare Crucible."] },
    defeatumbralsandsboss: { cat: "story",
      tip: ["Defeat Fuzan in Part IV of Icthlarin's Little Helper (Umbral Sands). It needs Black Knight's Fortress. Enter through the door to the Umbral Sands.",
            "Repair Icthlarin's mirrors, go to the volcanic gateway at the base of Fuzan's Volcano (The Burning Spire) and survive all ten waves of the Fight Cave to open Fuzan's Lair.",
            "Death in the Fight Cave drops your items and sends you to your bed. Build a lodestone at the entrance and bring Strong Tea for stamina.",
            "Fuzan resists fire and is immune to poison, bleed and burning. The wiki infobox lists power level 7; the strategy page says power level 6 gear."] },
    defeatkuldra: { cat: "story", wide: true,
      tip: ["Defeat Queen Kuldra in the Regicide quest, the final quest of Kuldra's Saga (added in 1.0). It needs Icthlarin's Little Helper.",
            "Kuldra is power level 9. You cannot damage her directly. Kill her dragon hatchlings for anima, charge the Anima Cannon, and hit her with six blasts in each of the first three phases. In the final phase you enter her body and attack her heart.",
            "The wiki strategy page is still marked under construction, so expect details to change."],
      steps: ["Finish Icthlarin's Little Helper",
              "Walk to the Dragon Gate north-west of Velgar's Rise (Fractured Plains) and enter the Scorned Wilderness",
              "Build a base at Rasthin's Rest and talk to Commander Zilyana",
              "Gear up: adamant or better pickaxe, rune or better logging axe, power level 7+ gear, antipoison, food, Strong Tea",
              "Clear the Scorned Wilderness raid",
              "Phase 1: kill the blue hatchling, feed the cannon, land 6 blasts, then hide in Zilyana's barrier",
              "Phase 2: kill the red hatchling, land 6 blasts",
              "Phase 3: platform to the main arena, land 6 blasts",
              "Phase 4: enter Kuldra and destroy her heart"] },

    // Regional quests. Any 3 secondary quests in the region count.
    brynmoor_questachievement: { cat: "quests", wide: true,
      tip: ["Complete any 3 secondary quests in Brynmoor. Steam misspells the description as \"Completer\".",
            "The wiki lists Growing Pains and Shrimp Catcher as tutorial secondary quests and names them as eligible. If they do not trigger it, finish the other three."],
      steps: ["Growing Pains - Wise Old Man, Bramblemead Village",
              "Shrimp Catcher - Wise Old Man, Bramblemead Village",
              "Restless Ghosts - crumbling well, Bramblemead Village",
              "Goblin Diplomacy - Zanik, Bramblemead Valley",
              "Highlighting the Problem - wizard statue in the Runecrafting Guild"] },
    ghornfell_questachievement: { cat: "quests", wide: true,
      tip: "Complete any 3 secondary quests in Ghornfell. Some region quests only start after you begin or finish the region's primary quest.",
      steps: ["Granite Mauled - Doric, Fractured Plains",
              "Heartstrings - memorial on the hilltop, Fractured Plains",
              "Dog Days - Vannaka, centre of the Stormtouched Highlands",
              "Cook's Assistant - Slopfinger, southern border of Stormtouched Highlands and Fractured Plains",
              "Animal Magnetism - Manktongue, same southern border",
              "A Room With A Garou - Caratacus, Fractured Plains",
              "A Melody Remembered - repair the broken music box in a desk in the Stormtouched Highlands",
              "The Great Body Robbery - Doctor Fenkenstrain, Bloodblight Swamp"] },
    fellhollow_questachievement: { cat: "quests", wide: true,
      tip: "Complete any 3 secondary quests in Fellhollow. Vannaka and Doric each give two, so those NPCs cover most of the goal.",
      steps: ["Even More Restless Ghosts - Zanik, Fellhollow",
              "The Wild Hunt - Vannaka, Bleaksfield Valley",
              "Things That Go Boom In The Night - Vannaka, Bleaksfield Valley",
              "Seeking Salvation - Doric, in a cave east of the Lake of Lost Souls",
              "Doric's Quest - Doric, same cave",
              "Letters for the Dead - Postie Pete, Forgotten Temple",
              "What Remains is Written - Abraxus The Eternal, Coalridge Pass",
              "Mirror, Mirror - the mirror west of the Guthix shrine near Emberwood"] },
    dowdun_reach_questachievement: { cat: "quests", wide: true,
      tip: "Complete 3 secondary quests in Dowdun Reach. The region has exactly three, so you need all of them.",
      steps: ["Biohazard - attack the corrupted raven in The Courtyard and pick up its drop",
              "Wanted! - Vannaka, The Courtyard",
              "What's Theirs is Mine! - Doric, next to the Dreaming Stone in The Nexus"] },
    umbral_sands_questachievement: { cat: "quests", wide: true,
      tip: ["Complete any 3 secondary quests in Umbral Sands. Steam writes \"Icthlarins\"; the quest giver is Icthlarin.",
            "The region has four. Anamcara gives both Mapping The Sands quests; part II likely follows part I."],
      steps: ["Contact! - Avisk Crystal, Dunes of Uzzer",
              "Brink of Extinction - Zi at The Burning Spire, south of the Sinking Pyramid",
              "Mapping The Sands I - Anamcara, Alcarrid Camp",
              "Mapping The Sands II - Anamcara, Alcarrid Camp"] },

    // Skill basics. Most unlock during the tutorial quests.
    attacknovice: { cat: "novice",
      tip: "Reach Attack 5 to unlock Parry. Hold a weapon or shield and hold right-click just before an enemy's hit lands." },
    magicnovice: { cat: "novice", flag: "spell",
      tip: ["Unlock the Fire Magic perk, equip a staff, load fire runes and hit any enemy.",
            "The 1.0 wiki lists Fire Magic at Magic 21. Dragonwilds Codex (0.12.1 data) lists it at Magic 8. The achievement page says \"Attack 21\", which looks like a typo. Check your Magic skill tree."] },
    rangednovice: { cat: "novice", flag: "spell",
      tip: ["Reach Ranged 8 for the Trick Shot perk. Fully draw and loose one arrow with a bow, keep aiming, then release the next arrow the moment a spark flashes at the arrow tip.",
            "A late release fires a normal shot. You can wait as long as you like between shots while you keep aiming."] },
    miningnovice: { cat: "novice",
      tip: "Mine any node: a stone boulder, clay, copper, tin or higher. This unlocks during the tutorial." },
    woodcuttingnovice: { cat: "novice",
      tip: "Chop down any standing tree. Picking up ash logs from the ground does not count." },
    artisannovice: { cat: "novice",
      tip: "Craft any weapon at a crafting table, blacksmith's bench or mystic forge. A stone dagger or stone club is the cheapest." },
    constructionnovice: { cat: "novice",
      tip: "Build a bed or bed roll and enclose it with at least four walls and a roof, then claim the bed. Ash log walls and a 45 degree roof cost about 22 ash logs." },
    cookingnovice: { cat: "novice",
      tip: "Cook any food item on a campfire, grill, stone range or cooking range." },
    runecraftingnovice: { cat: "novice",
      tip: "Craft any rune, either at a rune altar (auto-craft or attune rune essence) or at an anima vent." },
    farmingnovice: { cat: "novice",
      tip: "Plant any seed in a farming plot." },
    fishingnovice: { cat: "novice",
      tip: "Catch a fish from a net or rod fishing spot. Junk and other non-fish catches do not count." },

    // Skill challenges. Each needs a spell or perk from a skill tree.
    attackveteran: { cat: "veteran", flag: "spell",
      tip: ["Have a melee weapon both enchanted and honed at once. Cast Enchant Weapon: Fire (Attack 20, 15 fire and 5 astral runes) or Enchant Weapon: Air (Attack 30) on your held weapon, then use a whetstone on it.",
            "The whetstone recipe unlocks at Attack 40. Craft it at a blacksmith's bench from 5 granite and 10 stone. Fire enchant lasts 5 minutes and a whetstone 10, so apply both back to back."] },
    magicveteran: { cat: "veteran", flag: "spell",
      tip: ["Cast Confuse (Magic 30, 25 astral runes) on an aggressive monster standing near other monsters, then wait. Do not attack it, or the spell breaks.",
            "The kill must land while Confuse is still active. A burn that finishes the target after Confuse expires does not count.",
            "Confuse does not work on bosses, minibosses or training dummies. Greater Confuse (Magic 44) adds Garou thanes, dire wolves and KotHaar.",
            "The wiki says the pharaoh's sceptre special attack, Royal Mandate, also works."] },
    rangedveteran: { cat: "veteran", flag: "spell",
      tip: ["Cast Snare (Ranged 12, 15 astral and 10 nature runes), lure an enemy onto it, then hit the rooted enemy with an enhanced arrow.",
            "The wiki names poisoned arrows: Toxic Behaviour (Ranged 15) unlocks weapon poison, which you add to arrows at a fletching bench. Fire arrows and barbed arrows probably also count, but no source confirms it.",
            "Snare roots for 8 seconds, so have the poisoned arrows equipped before the enemy steps in."] },
    miningveteran: { cat: "veteran", flag: "spell",
      tip: ["Break 4 ore deposits with one cast of Rocksplosion (Mining 11). The spell page lists 15 earth and 5 fire runes; the achievement page says earth and astral. Carry both.",
            "The blast covers a 5-metre radius, so find a tight cluster of at least four nodes. Carry a pickaxe good enough for every node in the cluster. Ultimate Burst (Mining 51) widens the radius."] },
    woodcuttingveteran: { cat: "veteran", flag: "spell",
      tip: "Fell 3 trees with one cast of Axtral Projection (Woodcutting 11, 10 air and 5 astral runes). The axe flies 30 metres straight ahead, so stand where 3 trees line up. Carry a logging axe good enough for those trees." },
    artisanveteran: { cat: "veteran", flag: "spell",
      tip: ["Repair 3 items with one cast of Magical Mending. It moved from Artisan 27 to Artisan 56 in 1.0. It costs 20 earth and 10 nature runes.",
            "Drop three damaged tools, weapons or armour pieces on the ground close together, then cast. The items return to the nearest player's inventory in new slots, so do this somewhere safe."] },
    constructionveteran: { cat: "veteran", flag: "spell",
      tip: "Cast Eye of Oculus (Construction 11, 3 astral runes) and place any building piece while in the floating view. Carry the materials for that piece. The achievement page says Artisan 27, but the spell and Construction pages say Construction 11." },
    cookingveteran: { cat: "veteran", flag: "spell",
      tip: ["Make one iconic meal at a cooking range: a mushroom kebab, wild pie or meat pizza. The recipes unlock with Adept Culinaromancer at Cooking 36.",
            "Wild pie: fried onions, baked potato, dried dwellberries and bread. It gives a 10% XP boost for all skills, so make a stack for your 99 grinds.",
            "Mushroom kebab: grilled mushrooms, fried cabbage, haunch and bread. Meat pizza: flank steak, fillet, haunch and bread."] },
    runecraftingveteran: { cat: "veteran", flag: "spell",
      tip: ["Cast Runes to Rune Essence. It moved from Runecrafting 27 to Runecrafting 61 in 1.0. It costs 5 water and 5 astral runes, and you drop at least 10 runes on the ground as input.",
            "The wiki says this achievement does not unlock on dedicated servers. Cast it in a solo world."] },
    farmingveteran: { cat: "veteran", flag: "spell",
      tip: ["Harvest 24 plots with one cast of Uproot (Farming 15, 10 earth and 10 astral runes).",
            "Uproot covers a 15-metre radius. Harvester (Farming 36) raises it to 30 metres, which makes this far easier. Build 24 or more plots in a tight block, plant them all at once, and cast from the middle once every crop is ripe. Sleeping advances crops one growth stage per day."] },
    fishingveteran: { cat: "veteran", flag: "spell",
      tip: ["Cast Fishing Frenzy (Fishing 10, 15 water and 5 astral runes) on a fishing spot, then cast Fishnado (Fishing 55, 15 air and 5 nature runes) on the same spot while the frenzy lasts.",
            "Fishnado needs a net or rod of the spot's power level or better in your inventory. Both spells have long cooldowns, so line them up before you cast."] },

    // Hidden extras.
    hidden1novice: { cat: "hidden",
      tip: "Eat any fish-based food, such as fish fry, fried sardine, fried salmon or grilled trout." },
    hidden1veteran: { cat: "hidden", flag: "spell",
      tip: "Cast Enchant Weapon: Fire (Attack 20) or Enchant Weapon: Air (Attack 30) on a held melee weapon. Tools such as pickaxes do not count." },
    hidden1mastery: { cat: "hidden",
      tip: ["Have a food perk, an infusion perk and a potion perk active at the same time. One of each type stacks; a second food or potion replaces the first.",
            "Plain food without a perk does not count. A wild pie or mushroom kebab works for the food."],
      steps: ["Eat a perk food (for example wild pie)",
              "Drink an infusion (for example Redberry Infusion, made at a cooking range with clean water)",
              "Drink a potion (for example Lesser Attack Potion, made at a brewing cauldron)"] },
    hidden2mastery: { cat: "hidden", flag: "spell",
      tip: ["Kill a chicken with a fire spell from a staff. Unlock Fire Magic first (see Singed!).",
            "Chickens live in Temple Woods, Bramblemead Valley and Dowdun Reach. They have 20 health and are weak to fire. No source says whether fire arrows count, so use the staff."] },

    // Agility. Agility and its six courses arrived in patch 0.12.1.
    agilitynovice: { cat: "agility",
      tip: "Earn a gold medal on any course. Chasm Dash in Brynmoor needs no level; gold is 57 seconds or faster. Monsters do not attack on courses, and you can use spells but cannot build." },
    agilityveteran: { cat: "agility", flag: "spell", wide: true,
      tip: ["Earn a gold medal on every course. Lava Fields needs Agility 65, so this is the true requirement. Gold on all courses also unlocks the gilded gyrhawk amulet recipe (+25% course XP).",
            "Yellow stamina orbs on each course refill stamina. Press ESC or walk away to reset a bad run.",
            "The wiki course list predates 1.0. If the Scorned Wilderness added a course, it is not listed yet."],
      steps: ["Chasm Dash (Brynmoor, Agility 1) - gold at 0:57",
              "Fractured Ruins (Ghornfell, Agility 15, Windstep + Double Jump) - gold at 0:56",
              "Thunder Assault (Ghornfell, Agility 15, Windstep + Double Jump) - gold at 1:06",
              "Grave Run (Fellhollow, Agility 30, Windstep + Double Jump) - gold at 1:07",
              "Tower Climb (Dowdun Reach, Agility 51, Windstep + Double Jump + Air Dash) - gold at 1:09",
              "Lava Fields (Umbral Sands, Agility 65, Double Jump + Air Dash) - gold at 1:05"] },

    // Level 99 mastery. Level 99 needs 1,000,000 XP. Level 95 is 447,689 XP,
    // so the last four levels take more than half of the grind.
    agilitymastery: { cat: "mastery", flag: "grind", wide: true,
      tip: ["Run gold laps on the best course you can access. Lap counts below are from the wiki, without XP boosts.",
            "With a Focused Agility potion, the gilded gyrhawk amulet and a wild pie, Lava Fields drops to about 494 gold laps for 65 to 99. You also earn passive XP by running on foot (not on mounts) and by dodging attacks and vault traps."],
      steps: ["1-15: Chasm Dash, about 20 gold laps",
              "15-30: Thunder Assault, about 36 gold laps (slightly better than Fractured Ruins)",
              "30-51: Grave Run, about 93 gold laps",
              "51-65: Tower Climb, about 119 gold laps",
              "65: earn gold on every course, then craft the gilded gyrhawk amulet",
              "65-99: Lava Fields, about 885 gold laps unboosted or about 494 fully boosted"] },
    attackmastery: { cat: "mastery", flag: "grind", wide: true,
      tip: ["Damage comes from your weapon's power level, not your Attack level. Upgrade gear first; faster kills mean faster XP.",
            "Dragonwilds Codex (0.12.1 data) lists the Black Knight Titan at about 4,620 Attack XP per kill, the best listed rate. The wiki suggests Fight Cave waves for Attack."],
      steps: ["Brynmoor: loop rats and goblins from the Windmill to the Runecrafting Guild, the Keep of Blue Flames and the Adventurer's Guild",
              "Ghornfell: Wild Lapulis Vines in the Stormtouched Highlands (weak to melee) with bronze, then iron weapons",
              "Attack 40: craft whetstones and keep one active",
              "After Black Knight's Fortress: re-fight the Black Knight Titan",
              "After Icthlarin's Little Helper: clear Fight Cave waves 1 to about 30 and skip Fuzan",
              "Keep a wild pie (+10% XP) and a Lesser Attack Potion active"] },
    magicmastery: { cat: "mastery", flag: "grind", wide: true,
      tip: ["The wiki Magic training page is a stub. It lists the Black Knight Titan, other bosses and monster runs.",
            "Dragonwilds Codex (0.12.1 data) lists Magic XP per kill: Black Knight Titan about 3,500, Tok-Xil about 1,750, red dragon about 1,250, green dragon about 700."],
      steps: ["Magic 21: Fire Magic for area damage on groups",
              "Magic 30: Confuse; let enemies fight each other while you pick off survivors",
              "Mid game: dragons and Zogres",
              "After Black Knight's Fortress: re-fight the Black Knight Titan with water spells (his weakness)",
              "Keep a wild pie (+10% XP) and a Lesser Magic Potion active"] },
    rangedmastery: { cat: "mastery", flag: "grind", wide: true,
      tip: ["The wiki Ranged training page is a stub. It lists the Black Knight Titan, other bosses and monster runs.",
            "Dragonwilds Codex (0.12.1 data) lists Ranged XP per kill: Black Knight Titan about 3,500, Tok-Xil about 1,750, red dragon about 1,250. Ava's Accumulator saves arrows."],
      steps: ["Ranged 8: use Trick Shot on every volley for +15% damage",
              "Ranged 15 and 22: poisoned and barbed arrows",
              "Ranged 25: keep Spectral Arrows up",
              "After Black Knight's Fortress: re-fight the Black Knight Titan",
              "Keep a wild pie (+10% XP) active"] },
    miningmastery: { cat: "mastery", flag: "grind", wide: true,
      tip: ["Mine the highest ore you can, and cast Rocksplosion every time it comes off cooldown. When a region's nodes run dry, cycle back: adamantite, then mithril, then coal. Lower than coal is not worth it.",
            "Wear an inspiring ring of Mining when you cast Rocksplosion; swap to a damage amulet for manual mining."],
      steps: ["Mining 11: Rocksplosion",
              "Construction 40: Personal Chest spell for weightless ore storage",
              "Build lodestones next to ore clusters",
              "Mining 51: Ultimate Burst widens Rocksplosion",
              "Keep a Focused Mining potion and a wild pie (+10% XP) active"] },
    woodcuttingmastery: { cat: "mastery", flag: "grind", wide: true,
      tip: ["XP scales with damage dealt, so a better axe speeds up every tree tier. Use standard chops on standing trees and overhead chops on fallen trunks.",
            "Magic trees in the Scorned Wilderness give about 1,016 XP each, far above every other tree (yew about 209, willow about 226). They regrow every 1 to 2 in-game days.",
            "Mass method: plant two parallel rows of about a dozen trees, fell them all with Axtral Projection, then cast Splinter on the trunk piles and Trunk Totem while Splinter recharges."],
      steps: ["Early: ash and oak everywhere, with the best axe you own",
              "Fellhollow: willows around the ponds; build lodestones between clusters",
              "Dowdun Reach: maples in The Courtyard with a mithril axe; replant the seeds",
              "Umbral Sands: yews; manage the Scorch heat",
              "Scorned Wilderness: magic trees with a rune axe",
              "Keep a wild pie (+10% XP) active"] },
    artisanmastery: { cat: "mastery", flag: "grind", wide: true,
      tip: ["Sources are thin for Artisan. Dragonwilds Codex (0.12.1 data) rates Crystal Bow and Yew Shortbow at about 300 XP per craft, and Keris, Necromancer's Staff and TokTz-Ket-Xil at about 250.",
            "The wiki suggests a chit loop: buy dragonwolf hide from Iasadair - The Merchant for 45 garou chits, make draconic leather, and sell it back for 60."],
      steps: ["Craft the gear you need for each region as you progress",
              "Umbral Sands: run the dragonwolf hide loop for XP and chits",
              "Late game: craft the highest-XP bows and staffs",
              "Keep a wild pie (+10% XP) active"] },
    constructionmastery: { cat: "mastery", flag: "grind", wide: true,
      tip: ["The wiki has no Construction training guide. Dragonwilds Codex (0.12.1 data) lists XP per build: lodestone about 80, oak or iron chest about 62, rugs and agility flags about 60, most furniture about 40.",
            "Community guides describe building furniture, then dismantling it to recover the materials and building again. Some also describe reloading the world to reset a Construction cooldown. The wiki confirms neither; test it before you commit materials."],
      steps: ["Build a sawmill and stockpile planks",
              "Build lodestones in every region you train in (80 XP each)",
              "Build and dismantle chests or rugs in a loop",
              "Construction 40: Personal Chest",
              "Keep a wild pie (+10% XP) active"] },
    cookingmastery: { cat: "mastery", flag: "grind", wide: true,
      tip: ["Each cooked ingredient gives 10 XP, each meal 20 XP and each drink 15 XP.",
            "The wiki's best listed method: after Icthlarin's Little Helper opens the garou merchants, buy redberries at 3 garou chits each and cook them for 10 XP apiece. From Cooking 41 to 99 that is about 98,349 redberries unboosted, or about 65,501 with an inspiring ring of Cooking, a wild pie and a Focused Cooking potion.",
            "Use the Personal Chest spell to carry about 5,148 redberries per trip, and build a lodestone near a merchant."],
      steps: ["Cook everything you gather while you play",
              "Cooking 36: make wild pies for the +10% XP buff",
              "Finish Icthlarin's Little Helper and farm garou chits",
              "Buy and cook redberries until 99, with ring, wild pie and potion active"] },
    runecraftingmastery: { cat: "mastery", flag: "grind", wide: true,
      tip: ["Craft the highest rune you can. From Runecrafting 50, law runes take about 13,000 rune essence to reach 99 with a Focused Runecrafting potion, the inspiring ring of Runecrafting and a wild pie, assuming 50 essence and a perfect attunement each time. Unboosted it takes about 19,000.",
            "Runes to Rune Essence (61) returns 40% of dropped runes as essence, and 60% at 81. The wiki reports the spell currently returns random amounts, so do not rely on the math. Siphon every anima vent you pass."],
      steps: ["1-3: air runes",
              "3-15: astral runes",
              "15-25: earth runes",
              "25-38: fire runes",
              "38-50: nature runes",
              "50-99: law runes with all boosts and perfect attunements",
              "61: recycle runes with Runes to Rune Essence"] },
    farmingmastery: { cat: "mastery", flag: "grind", wide: true,
      tip: ["Sources are thin for Farming XP rates; the wiki's methods section is mostly empty.",
            "Farming is passive, so train it alongside other skills. Plant seeds in their matching plots to cut disease, water crops to speed growth, and sleep to push every crop one stage forward.",
            "Iron secateurs raise the yield but do not work with Uproot or Harvester."],
      steps: ["Farming 15: Uproot for fast harvests",
              "Farming 28: Humidify for watering",
              "Build rain catchers and wells next to the plots",
              "Farming 36: Harvester (30-metre radius); also gets Gotta Patch 'Em All",
              "Farming 60: super compost bin",
              "Keep a wild pie (+10% XP) active"] },
    fishingmastery: { cat: "mastery", flag: "grind", wide: true,
      tip: ["Sources are thin for Fishing XP rates. The wiki says Fishnado gives 20 base XP per cast plus XP per fish pulled out. Fishing Frenzy doubles the fish but not the XP.",
            "Use the best rod or net you have, carry the Personal Chest spell for storage, and repair gear on the spot with Magical Mending."],
      steps: ["Fishing 10: Fishing Frenzy for extra fish",
              "Fishing 55: Fishnado on cooldown",
              "Fishing 60: Greater Fishnado (shorter cooldown)",
              "Fishing 70: craft the Angler's hat (10% chance not to deplete a spot)",
              "Keep a Focused Fishing potion and a wild pie (+10% XP) active"] },
  },
};
