// Guide data for the Baldur's Gate 3 tracker.
// Sources:
//   bg3.wiki achievement pages and community guides
//     (https://bg3.wiki/wiki/Achievements, https://bg3.wiki/wiki/Leave_No_One_Behind,
//      https://bg3.wiki/wiki/Guide:She_Cannot_Be_Caged!, https://bg3.wiki/wiki/Guide:Under_Lock_and_Key,
//      https://bg3.wiki/wiki/Guide:Fancy_Footwork_(achievement), https://bg3.wiki/wiki/Guide:No_Free_Lunches,
//      https://bg3.wiki/wiki/Punch_Drunk).
//   Steam guide "An Overly Descriptive BG3 Achievement Guide" by PersePhony
//     (https://steamcommunity.com/sharedfiles/filedetails/?id=3414533147), written on Patch 7.
//   Steam guide "Achievement guide 100% - Baldur's Gate 3"
//     (https://steamcommunity.com/sharedfiles/filedetails/?id=3018760696), plus its comments.
// Keys are lower-case Steam API names, so Steam unlocks match exactly.
// `steps` become a per-achievement checklist saved in the browser.
// Flags: "ending" (one per playthrough, keep a save), "missable" (act-locked),
// "run" (single-playthrough condition), "urge" (Dark Urge origin only).
//
// Playthrough plan (also on the "All's Well That Ends Well" card):
//   Run 1: Dark Urge, Tactician if you can, tiefling-aligned. Stack every missable, every
//   companion achievement, Busker, Punch Drunk and Jack-of-all-Trades. Branch saves at Orin,
//   at the Astral Prism talk, and at the final Netherbrain choice cover all five endings.
//   Run 2: Honour mode for Foehammer. Play safe; skip the risky boss conditions.
window.GUIDE = {
  appid: "1086940",
  title: "Baldur's Gate 3",
  titleAccent: "3",
  subtitle: "Achievement tracker, synced from Steam",
  credit: "Tips from bg3.wiki and the Steam guides \"An Overly Descriptive BG3 Achievement Guide\" (PersePhony) and \"Achievement guide 100% - Baldur's Gate 3\".",
  defaultStatus: "todo",
  storageKey: "bg3-tracker-v1",
  colors: {
    light: { accent: "#a3242e", accent2: "#1f6f78" },
    dark: { accent: "#ff6b6b", accent2: "#5fd0d6" },
  },
  flags: {
    missable: { label: "Missable: act-locked", tone: "accent" },
    ending: { label: "Ending: one per playthrough", tone: "accent2" },
    run: { label: "Single-playthrough condition", tone: "accent2" },
    urge: { label: "Dark Urge origin only", tone: "accent" },
  },
  highlight: { flag: "missable", label: "Remaining missables", note: "Finish these before the act ends" },
  categories: [
    ["story", "Story"],
    ["endings", "Endings"],
    ["missable", "Missable quests"],
    ["companions", "Companions & romance"],
    ["bosses", "Bosses with conditions"],
    ["playthrough", "Whole-playthrough goals"],
    ["tricks", "Combat & system tricks"],
    ["difficulty", "Difficulty"],
  ],
  achievements: {
    // ---------- Story ----------
    bg3_quest01: { cat: "story",
      tip: "Finish the prologue on the nautiloid." },
    bg3_quest02: { cat: "story",
      tip: ["Unlocks when you enter the Shadow-Cursed Lands, through the Mountain Pass or the Underdark.",
            "Before you go, finish every Act 1 missable: Pest Control, A Grym Fate, Forged in Blood and Fire, Taking Blood, Rude, Crude, and Full of Attitude, Sazza parts 1-2, the Leave No One Behind Act 1 steps, and recruiting Scratch and the owlbear cub."] },
    bg3_quest03: { cat: "story",
      tip: ["Unlocks when you leave the Mind Flayer Colony for Baldur's Gate.",
            "Before you enter the Shadowfell at the end of the Gauntlet of Shar, finish Under Lock and Key, Sazza part 3, Penny Pincher, Non-Invasive Procedure, the orchid for Shadowheart, the Act 2 heart fix for Karlach, and the Act 2 tiefling steps."] },
    bg3_quest04: { cat: "story", wide: true,
      tip: ["Finish the game with any ending. This card holds the playthrough plan.",
            "Run 1 (Dark Urge, tiefling-aligned, Tactician if you can): every achievement except Foehammer fits in one save file. One guide calls it theoretically possible. It needs Sazza and every tiefling saved in the same run, plus replays of the finale.",
            "Run 2 (Honour mode): aim only for Foehammer. Skip boss conditions that risk a wipe.",
            "Mods: disable them. Achievements are off while mods are active."],
      steps: [
        "Run 1: pick The Dark Urge origin (needed for Embrace Your Urge and Sins of the Father)",
        "Run 1: Act 1 missables done before leaving (see The Plot Thickens)",
        "Run 1: Act 2 missables done before entering the Shadowfell (see The City Awaits)",
        "Run 1: Act 3 - Busker, Punch Drunk, Mind Blown, Jack-of-all-Trades, Murder in Baldur's Gate, Fancy Footwork, Crash Landing",
        "Run 1: SAVE A before talking to Orin in the Temple of Bhaal",
        "Run 1 branch 1: refuse the Slayer, fight Orin normally for First Blood",
        "Run 1 branch 1: SAVE B before the final Astral Prism talk with the Emperor and Orpheus",
        "Run 1 branch 1: kill the red dragon in the Upper City (Interfectorem Draconis)",
        "Run 1 branch 1: SAVE C before the final Netherbrain choice, then take Hero of the Forgotten Realms",
        "Run 1 branch 1: reload SAVE C, take Absolute Power Corrupts",
        "Run 1 branch 1: reload SAVE B, become the mind flayer, finish for Ceremorphosis",
        "Run 1 branch 2: reload SAVE A, accept the Slayer (Embrace Your Urge), finish with Sins of the Father",
        "Run 2: Honour mode for Foehammer (see its checklist)",
      ] },
    bg3_quest11: { cat: "story",
      tip: ["Reach the Goblin Camp to trigger the cutscene where Shadowheart's artifact protects the party. Long rest afterwards.",
            "Open the Illithid powers tab and unlock any power. Eat a tadpole from a True Soul if you have no spare. No downside before Act 3."] },

    // ---------- Endings ----------
    bg3_quest05: { cat: "endings", flag: "ending",
      tip: ["At the final Netherbrain choice, pick the option to dominate the brain and become the Absolute.",
            "A guide comment reports you must NOT be the Slayer (Dark Urge) for this one. Do it on the branch where you refused Bhaal.",
            "The Steam guide reports this can unlock on the same ending as Ceremorphosis if you are the illithid. Unverified."] },
    bg3_quest06: { cat: "endings", flag: "ending",
      tip: ["At the final Netherbrain choice, destroy the brain and the Absolute.",
            "The Overly Descriptive guide reports it also unlocks from the early bad ending: let Gale detonate his orb during the Ketheric confrontation in the Mind Flayer Colony. The game autosaves before that room, so you can reload. Needs Repairing the Weave first. Treat as unverified."] },
    bg3_quest07: { cat: "endings", flag: "urge",
      tip: ["Dark Urge only. Needs the Slayer form: accept Bhaal's gift (Embrace Your Urge). Then at the final Netherbrain choice, claim the brain in Bhaal's name.",
            "A guide commenter confirmed the option does not appear unless you are the Slayer. Play this on the Slayer branch from your Orin save."] },
    bg3_quest08: { cat: "endings", flag: "ending",
      tip: ["In the final Astral Prism conversation with the Emperor and Orpheus, offer to become the mind flayer yourself.",
            "Play the Upper City finale as the illithid and finish the epilogue. Keep a save before that conversation; it comes before the final battle, so it is a separate save from the Netherbrain choice.",
            "One guide commenter did not get it on the first try and got it on reload. Unclear why."] },
    bg3_quest52: { cat: "endings", flag: "urge",
      tip: ["Dark Urge only. Accept Bhaal's offer to become his Slayer.",
            "Act 3 route: in the Temple of Bhaal, accept the Slayer role in the talk with Orin and duel her alone. Solo, she gets no Unstoppable stacks, so you can knock her off the ledge. Avoid being hit five times; she gets a strong multi-attack.",
            "Act 2 route (per the 100% guide): kill Isobel for the Urge, and Sceleritas grants the Slayer form at night. That makes Last Light fall and fails Leave No One Behind. Use the Act 3 route on a full run.",
            "The Act 3 route conflicts with First Blood. Save before Orin and branch."] },
    bg3_quest25: { cat: "missable",
      tip: ["Any origin, not Dark Urge only. Finish the Investigate the Murders quest in Act 3 by joining the Bhaalists and killing Valeria.",
            "Start: Valeria at the Rivington monk temple, then the red wardrobe two floors up in Fraygo's Flophouse (Bloodstained Parchment), show it to Valeria at Sharess' Caress, then Devella upstairs in the Elfsong Tavern for the murder map.",
            "To reach the Murder Tribunal you need a victim's hands and the password \"Sicarius\". Easiest: kill Dolor at the wine festival (warn Cora; Counterspell his Dimension Door) and loot his bag of hands and the torn page. Other routes: kill two of Dolor's victims, or kill Gortash for Orin.",
            "Enter Candulhallow (X: 74 Y: 25), move the butterfly painting, press the button, walk the brick path. Show the hands to the knight, lie to Sarevok that you killed the victim, then kill Valeria in the Abattoir."] },

    // ---------- Missable quests ----------
    bg3_quest22: { cat: "missable", flag: "missable",
      tip: ["Rescue the goblin Sazza three times: Emerald Grove, Goblin Camp, Moonrise Towers. Possible on a tiefling run; the steps follow the bg3.wiki guide.",
            "If you want to keep Minthara as a companion, knock her out non-lethally instead of killing her.",
            "The Overly Descriptive guide gives another Goblin Camp method (kill Gut only, back Sazza, knock out Minthara and Sazza non-lethally) and warns it may be outdated since Patch 8."],
      steps: [
        "Act 1 Grove: convince the tieflings not to kill Sazza",
        "Act 1 Grove: escort her out through the hidden cave path west of the gate, or out the main gate by passing the checks",
        "Act 1 Goblin Camp: in Minthara's chamber say \"She had no idea.\"",
        "Act 1 Goblin Camp: agree to attack the Grove (\"I'll get it done.\") - this part now counts",
        "Act 1: long rest, talk to Zevlor, then betray Minthara and defend the Grove",
        "Act 2: enter Moonrise Towers before the assault with Jaheira and before the Shadowfell",
        "Act 2 Moonrise throne room: vouch for the goblins with Ketheric and Z'rell, then release them",
      ] },
    bg3_quest24: { cat: "missable", flag: "run", wide: true,
      tip: ["Keep 15 tieflings alive all game: Alfira, Arabella, Bex, Cal, Cerys, Dammon, Danis, Ide, Lakrissa, Lia, Mol, Rolan, Umi, Zevlor, Zorru. It unlocks on finishing the game, so you only learn the result at the credits.",
            "Scripted deaths and disappearances in Act 2 do not count against you.",
            "Sources disagree on Mirkon (harpies) and Nadira (bugbear). The 100% guide says save them; bg3.wiki and several players say they are optional. Save them anyway to be safe.",
            "Clear the goblin leaders yourself before the raid. Defending the Grove risks tiefling deaths."],
      steps: [
        "Act 1: persuade Rolan to stay with his siblings and the refugees",
        "Act 1: convince Kagha to spare Arabella in the Inner Sanctum",
        "Act 1 (Dark Urge only): knock Alfira out non-lethally during her camp event so the bard Quil replaces her",
        "Act 1: stop the Rite of Thorns (killing the goblin leaders does it)",
        "Act 1: optional - save Mirkon from the harpies and Nadira from the bugbear",
        "Act 1: all 11 Grove tieflings alive when Defeat the Goblins completes; if Cerys appears in Act 1, Zevlor died and the run failed",
        "Act 2: save Rolan from two Shadows at the Ruined Battlefield (X: -54 Y: -111)",
        "Act 2: protect Dammon if you fight the Strange Ox",
        "Act 2: finish Find Arabella's Parents (House of Healing, X: -185 Y: 12; Speak with Dead on her father)",
        "Act 2: rescue Cal, Danis, Lakrissa, Lia from the Moonrise prison, then talk to Alfira at Last Light",
        "Act 2: side with Isobel in Resolve the Abduction; Last Light, Isobel and all tieflings must survive",
        "Act 2: enter the Shadowfell only after all the above; spare the Nightsong",
        "Act 2: free Zevlor from his pod in the Mind Flayer Colony and keep him alive",
        "Act 3: protect Rolan if you fight Lorroakan",
        "Act 3: find Mol at the Guildhall; side with the Guild in Aid the Underduke and protect her",
        "Act 3: do not summon Zevlor for the final battle, or keep him alive if you do",
      ] },
    bg3_quest21: { cat: "missable", flag: "missable",
      tip: ["Free all seven prisoners in the Moonrise Towers prison: Cal, Danis, Lia, Lakrissa, Wulbren, Nickels, Nimble. Guards try to kill them during the escape.",
            "Safe route (bg3.wiki): kill every Scrying Eye and guard first, then toss Wulbren his hammer or any bludgeoning weapon.",
            "Combat route: kill the warden alone in her office, knock Adept Keris and Zealot Nadi into the chasm, then pull every office lever except the big one."],
      steps: [
        "Act 1: save Barcus on the Blighted Village windmill (pull the brake lever)",
        "Act 1 Grymforge: save the gnomes, kill Nere, promise Barcus you will save Wulbren",
        "Act 1: do not long rest twice after hearing Nere's voice, or he dies",
        "Act 2: talk to the tieflings in the prison and to Wulbren",
        "Act 2: kill the warden, guards, and Scrying Eyes (or sneak per the guide)",
        "Act 2: give Wulbren a bludgeoning weapon and break the boat chains",
        "Act 2: all 7 on the boat - Cal, Danis, Lia, Lakrissa, Wulbren, Nickels, Nimble",
        "Act 2: talk to Alfira, Wulbren, and the rescued tieflings at Last Light",
      ] },
    bg3_quest23: { cat: "missable", flag: "missable",
      tip: ["Act 1. Finish Find the Blood of Lathander under Rosymorn Monastery.",
            "Place the three ceremonial weapons (mace from the kobolds, axe near the Guardian of Faith, hammer from the eagle nest) on their pedestals for the crest. Generic mace, battleaxe, and warhammer also work, per the Overly Descriptive guide.",
            "After the Inquisitor, turn the south statue west and the north statue east, then destroy the blue crystals with ranged attacks. The crest keeps the traps off."] },
    bg3_quest19: { cat: "missable", flag: "missable",
      tip: ["Act 1. In the Blighted Village, find the secret cellar in the herb house (Perception check). In the coffin room, open the coffin immediately to your right as you enter: it holds the Summon Quasit scroll.",
            "Read the scroll or learn it, then summon Shovel. Do not rename her; renaming reportedly bugs the achievement."] },
    bg3_quest20: { cat: "missable", flag: "missable",
      tip: ["Act 1 Grymforge. Get a mould from the hanging platforms and mithral ore from the glowing blue rocks by the lava.",
            "Put the mould in the chamber and the ore in the crucible, pull the forge lever, shoot the lava valve, and beat Grym. Then forge your item. Do it together with A Grym Fate."] },

    // ---------- Companions & romance ----------
    bg3_quest50: { cat: "companions",
      tip: "Let Astarion bite you in his early night scene." },
    bg3_quest45: { cat: "companions", flag: "missable",
      tip: ["Recruit Scratch in Act 1: forest east of the Blighted Village entrance, mourning his dead master. Calm him and invite him to camp.",
            "After some long rests he brings you his ball. Throw it where he can reach it; the achievement pops when he returns it. The event can come later than Act 1, but the recruit cannot."] },
    bg3_quest18: { cat: "companions", flag: "missable",
      tip: ["Recruit both Scratch and the owlbear cub, then wait for a camp event where you hear animal noises and pet both.",
            "Cub: in the Owlbear Cave, leave without a fight or kill the mother and spare the cub. Do not attack from stealth. Do not recruit the two Absolutists outside the Grove.",
            "At the Goblin Camp, win the chicken-chase game (Speak with Animals lets you tell the cub to run to the pillars), persuade Krolla to free it, and invite it to camp. Later feed it, then heal it the next night.",
            "Sources disagree on Speak with Animals while petting: the Overly Descriptive guide suggests it; the 100% guide says it blocks the achievement. Pet without it."] },
    bg3_quest48: { cat: "companions", flag: "missable",
      tip: ["Talk to Shadowheart often until she speaks of Shar. At camp, pick \"Tell me something about yourself besides Shar, besides tadpoles\" to learn about night orchids.",
            "You get that option once. If you missed it, cast Disguise Self and ask again (tip from a guide commenter).",
            "Act 2: pick the night orchid on the ledge in front of the Ruined Battlefield waypoint (X: 57 Y: 179) and talk to her with it in your pack."] },
    bg3_quest49: { cat: "companions", flag: "missable",
      tip: ["Romance Karlach across all three acts. Keep Wyll from killing her at the Risen Road.",
            "Collect Infernal Iron. Stock at least two."],
      steps: [
        "Act 1: recruit Karlach, kill the Paladins of Tyr for her",
        "Act 1: give Dammon an Infernal Iron with Karlach present; say \"I still can't touch you though...\" then \"Of course I do\"",
        "Act 1: choose Karlach at the tiefling party",
        "Act 2: give Dammon a second Infernal Iron at Last Light; get her romance scene before Act 3",
        "Act 3: in the Lower City say \"It's been a long time since we last connected\"; the date follows a long rest",
      ] },
    bg3_quest26: { cat: "companions",
      tip: ["Act 3. Finish Visit the Emperor's Old Hideout: storeroom under the Elfsong Tavern. Beat or intimidate Har'rak (Lae'zel helps), then inspect the Emperor's things.",
            "Next long rest, hold the Emperor's hand. The long rest after, accept his advances. It does not affect other romances. Do it right after Punch Drunk; both start in the Elfsong."] },
    bg3_quest46: { cat: "companions", flag: "missable",
      tip: ["Keep Gale alive and in camp. Feed him three magic items when he asks in Act 1. Keep medium approval.",
            "Good cheap feeds near the Grove: Komira's Locket (save Arabella), Ring of Color Spray (harpies), Cap of Curing (next to Alfira).",
            "Elminster arrives on the way into Act 2. Invite him to camp and finish the talk."] },
    bg3_quest51: { cat: "companions", flag: "missable",
      tip: ["Recruit Wyll and meet Mizora at camp. Needs steps in all three acts.",
            "The Act 3 step is the part sources describe least clearly. Follow the checklist and keep a save before the camp talk."],
      steps: [
        "Act 1: recruit Wyll; meet Mizora during a long rest",
        "Act 2: when Mizora asks you to free a devil, persuade her to release Wyll's pact in return",
        "Act 2 Mind Flayer Colony: find Mizora in a pod near Zevlor, bargain again (DC 14 Persuasion), pull the Unleash lever",
        "Act 3 Wyrm's Rock: talk to Mizora, talk to Gortash, then talk to Mizora again",
        "Act 3 camp: when Mizora and her sisters appear, tell Wyll to break the pact (the Duke's rescue gets harder)",
      ] },
    bg3_quest47: { cat: "companions", flag: "missable",
      tip: ["Side with Voss. Do not fight him at the Mountain Pass. The Overly Descriptive guide says you may need Lae'zel in the party.",
            "After the Inquisitor in the Creche, speak with Vlaakith and agree to visit your Guardian, but do not kill it. Leaving triggers a forced long rest where Voss offers an alliance. Accept.",
            "The 100% guide says the scene can come on arrival in Act 2 instead."] },

    // ---------- Bosses with conditions ----------
    bg3_quest31: { cat: "bosses",
      tip: ["Defeat Zhalk in the last nautiloid room. Hard with prologue tools. Explorer halves his HP and delays the cambions to turn 7; the achievement still counts.",
            "Prep: free Us, prepare Command on Shadowheart (Command: Drop disarms him for good), stack chests in the doorway to block the cambions, refresh at the pod. Do not climb the second stairs.",
            "A recent comment on the 100% guide reports the mind flayer killing him still counts."] },
    bg3_quest32: { cat: "bosses", flag: "missable",
      tip: ["Act 1, Whispering Depths (the Blighted Village well). Kill the Spider Matriarch before she hatches any egg. She hatches intact eggs on turn 1, so you know at once if you failed.",
            "Take the Spiderstep Boots from the side cave. Burn the three egg clusters with fire from stealth: Alchemist's Fire for the low west cluster, Fire Bolt for the east one, then the central one.",
            "Or shoot the web bridge when she walks over it; the fall deals about 45. On Balanced you can sneak up and shove her into the chasm."] },
    bg3_quest33: { cat: "bosses", flag: "missable",
      tip: ["Act 1 Grymforge. Kill Grym without using the forge hammer lever. Grym only takes damage while Superheated in lava, so shoot the lava valve each time it cools.",
            "Cheese: throw water from the stairs for bludgeoning damage and Misty Step between staircases. Or \"Owlbear from the top ropes\": a level 6 druid owlbear with Enlarge and Elixir of the Colossus uses Crushing Flight from the stairs.",
            "Pair with Forged in Blood and Fire."] },
    bg3_quest34: { cat: "bosses", flag: "missable",
      tip: ["Act 2, House of Healing. Kill Malus Thorm before he uses a surgery attack on anyone.",
            "Bring only the face: persuade him (DC 21) to make the nurses operate on each other so they die first. Then fight him; do not talk him into killing himself.",
            "Park the rest of the party on the stairs above, out of his reach. Grease slows him when he tries to revive a nurse."] },
    bg3_quest35: { cat: "bosses", flag: "missable",
      tip: ["Act 2, Reithwin tollhouse. Defeat Gerringothe Thorm before she uses gold against you.",
            "Talk route: pay the first coin, never admit you are broke, then win the DC 18 check (gold is meaningless, she is corrupt, her job is gone). She bursts into coins with full XP.",
            "Combat routes: shove her out a window from stealth and finish her below, or shoot the flying skull heads from stealth to strip her armour first."] },
    bg3_quest36: { cat: "bosses", flag: "missable",
      tip: ["End of Act 2, Mind Flayer Colony. Kill the Apostle of Myrkul (Ketheric's phase 2) before he eats any necromite. Do not talk Ketheric into repenting.",
            "Kill necromites and involucres as they spawn. AoE terrain over his pool helps (Wall of Fire, Hunger of Hadar, Black Tentacles). Darkness on the Apostle also works (bg3.wiki).",
            "Burst option (bg3.wiki): 20 smokepowder bombs, Alert, Callous Glow Ring. Throw one stack at Ketheric from a ledge, then one at the Apostle."] },
    bg3_quest37: { cat: "bosses",
      tip: ["Act 3, Wyrm's Rock. Defeat Gortash without setting off a trap. Save before the coronation first.",
            "Spirit Guardians trick: neutral NPCs flee it, so you can herd Gortash out of the room without combat, down the stairs and onto a balcony or the bridge, then shove or throw him off.",
            "Killing him that way turns the fortress hostile, blocks the Grand Duke rescue and the Iron Throne prisoners. Reload after the achievement if you need them.",
            "Normal fight: shoot the traps from the staging room before the fight (Ctrl to target objects)."] },
    bg3_quest38: { cat: "bosses",
      tip: ["Act 3, Temple of Bhaal. Kill Orin while the cultists still chant: do not kill or disrupt them first.",
            "Upcast Magic Missile strips her Unstoppable stacks. On Tactician or lower, Repelling Blast can push her off the ledge.",
            "Not Dark Urge only, but a Dark Urge cannot take the solo duel for this. You can accept and then bring the party in to cancel the duel.",
            "A commenter reports the cultists sometimes skip the chant; starting before talking to Orin fixed it for them."] },
    bg3_quest39: { cat: "bosses",
      tip: ["Kill the dominated red dragon guarding the Crown of Karsus in the final Upper City battle.",
            "Spread out against its fire and fear. Gather Your Allies can tank the adds. It lands on every ending branch, so any of them works."] },
    bg3_quest40: { cat: "bosses",
      tip: ["Act 3. Take Ansur down while he flies and uses Gather Power (he takes off near half health and resists all damage while charging).",
            "Reach him: in Wyrm's Rock prison, hit both dragon-head statues with lightning, then clear the four Wyrmway trials.",
            "Sources differ on how to do it. The Overly Descriptive guide says kill him mid-flight and confirms Mind Blast stun also worked. The 100% guide suggests Banishment at takeoff. Bring level 12, lightning resistance, and burst."],
      steps: [
        "Justice: Remove Curse on the Judge, place the Cell painting in the niche",
        "Insight: attack Suelto exactly once",
        "Strategy: destroy the black king with lightning",
        "Courage: one character talks to the statue, then Sanctuary or Feign Death for 4 turns",
      ] },

    // ---------- Whole-playthrough goals ----------
    bg3_quest09: { cat: "playthrough",
      tip: "Complete ten background goals in one run." },
    bg3_quest10: { cat: "playthrough",
      tip: "Take four full long rests in one run." },
    bg3_quest12: { cat: "playthrough",
      tip: "Dig up five buried chests with a shovel." },
    bg3_quest17: { cat: "playthrough", flag: "run",
      tip: ["Brew three different potions in the Alchemy tab in one run.",
            "Extract All Ingredients to unlock recipes, then craft the missing extracts for three recipes."] },
    bg3_quest43: { cat: "playthrough", flag: "run",
      tip: "Read 100 different books in one run. Scroll each to the last page; only a full read counts." },
    bg3_quest28: { cat: "playthrough", flag: "run",
      tip: ["Earn 100 gold from Perform in one run. After a successful Performance roll, each watching NPC tosses a coin, so you need about 100 onlookers in total.",
            "Bards have Perform. Use high Charisma and the Actor feat; one guide recommends hiring Brinna Brightsong from Withers for this.",
            "Play in crowded Act 3 areas (Lower City, Rivington). The 100% guide says the same NPC does not pay twice in a row; move between crowds. The counter lags, and you do not need to pick up the coins."] },
    bg3_quest44: { cat: "playthrough", flag: "run",
      tip: ["Defeat 20 enemies with a drunk party member in one run. Only the drunk character's killing blows count. Drink before or during combat.",
            "Act 3: Roveer's Storehouse (Elfsong Tavern kitchen). Send a drunk character down with Spirit Guardians up; the 1 HP rats die in droves.",
            "Act 2 alternative: touch the dead cursed raven at X: 29 Y: 118 in the Shadow-Cursed Lands; 1 HP ravens spawn."] },
    bg3_quest16: { cat: "playthrough", flag: "run", wide: true,
      tip: ["Take one level in each of the 12 classes on one character without a respec. The level cap is 12, so every level-up must add a new class.",
            "Easiest: reach level 12, hire a hireling from Withers (starts at level 1; also unlocks Outsourcing), and add a new class each level. Or leave a companion at level 1 in camp all game (100% guide).",
            "Do not ask Withers to change that character, ever. The 100% guide warns such a build is near useless on Tactician; keep it on the bench."],
      steps: ["Barbarian", "Bard", "Cleric", "Druid", "Fighter", "Monk", "Paladin", "Ranger", "Rogue", "Sorcerer", "Warlock", "Wizard"] },
    bg3_quest15: { cat: "playthrough",
      tip: "Talk to Withers at camp after recruiting him from the Dank Crypt, and hire a hireling. Use the hireling for Jack-of-all-Trades." },

    // ---------- Combat & system tricks ----------
    bg3_quest13: { cat: "tricks",
      tip: "Use Detect Thoughts in dialogue." },
    bg3_quest14: { cat: "tricks",
      tip: "Get arrested and break out of the cell." },
    bg3_quest29: { cat: "tricks",
      tip: "Make five attacks in one turn." },
    bg3_quest27: { cat: "tricks",
      tip: ["Use the Improvised Melee Weapon action on a small enemy and hit another enemy with it.",
            "Needs a high-Strength character. Mephits, imps, and goblins are good targets."] },
    bg3_quest30: { cat: "tricks",
      tip: "Unequip weapons and finish a weakened enemy with Unarmed Strike. A Monk gets it naturally." },
    bg3_quest41: { cat: "tricks",
      tip: ["Long rest using only alcohol as camp supplies. You need 40 supply value, 80 on Tactician and Honour.",
            "Pick supplies manually. The only cost is a short hangover."] },
    bg3_quest42: { cat: "tricks",
      tip: ["Kill a creature with fall damage: Shove (V), Thunderwave, or Repelling Blast near a ledge.",
            "Fastest: shove a companion into a chasm; it always succeeds. Save first."] },

    // ---------- Difficulty ----------
    bg3_quest53: { cat: "difficulty", flag: "run",
      tip: ["Finish the whole game on Tactician without lowering the difficulty.",
            "Do run 1 on Tactician if you are comfortable; everything else fits in that run.",
            "The Overly Descriptive guide says Foehammer also unlocks Critical Hit. Other sources do not confirm it; treat it as a fallback."] },
    bg3_quest54: { cat: "difficulty", flag: "run", wide: true,
      tip: ["Finish the game in Honour mode: one save, no reloads, bosses with legendary actions. If the party wipes, the run drops to Custom mode and the achievement is lost.",
            "Shortcut reported by guides: with Repairing the Weave done, let Gale detonate the orb at the Netherbrain before climbing the brainstem. That skips both final fights and still counts. Doing it at the end of Act 2 ends the run early; use the Act 3 finale."],
      steps: [
        "Disable all mods",
        "Plan a strong, simple build; know the boss legendary actions",
        "Skip risky optional fights and the boss-condition achievements",
        "Keep Gale alive and feed him artifacts (needed for the orb shortcut)",
        "Stock healing, scrolls of Revivify, and elixirs before each act boss",
        "Avoid fights near chasms and pushers without Feather Fall",
        "Pause and think before every dialogue check with death stakes (Astarion bite, Raphael deals)",
        "At the Netherbrain, let Gale detonate the orb before the brainstem climb",
      ] },
  },
};
